"""Seed 01 — AMD CPUs (AM5 Ryzen 9000/8000 + AM4 Ryzen 5000/4000/3000 series)."""

from models import db, CPU, CpuSocket


def _socket(name):
    return CpuSocket.query.filter_by(name=name).first()


def _add(cpus):
    for c in cpus:
        if not CPU.query.filter_by(name=c["name"]).first():
            db.session.add(CPU(**c))
    db.session.flush()


def seed():
    am5 = _socket("AM5")
    am4 = _socket("AM4")

    # ── Ryzen 9000-series (AM5 / Granite Ridge / Strix Halo) ────────────
    _add([
        dict(name="AMD Ryzen 9 9950X3D Dual Edition", brand="AMD", socket_id=am5.id,
             architecture="Zen 5", series="Ryzen 9000",
             cores=16, threads=32, base_clock_ghz=4.3, boost_clock_ghz=5.6,
             tdp_watts=200, max_tdp_watts=230, memory_type="DDR5",
             max_memory_speed_mhz=6400, memory_channels=2, pcie_gen=5,
             integrated_graphics=True, igpu_model="AMD Radeon Graphics", igpu_cores=2,
             cooler_included="Not Included", has_unlocked_multiplier=True, lithography_nm=4),

        dict(name="AMD Ryzen 9 9950X3D", brand="AMD", socket_id=am5.id,
             architecture="Zen 5", series="Ryzen 9000",
             cores=16, threads=32, base_clock_ghz=4.3, boost_clock_ghz=5.7,
             tdp_watts=170, max_tdp_watts=200, memory_type="DDR5",
             max_memory_speed_mhz=6400, memory_channels=2, pcie_gen=5,
             integrated_graphics=True, igpu_model="AMD Radeon Graphics", igpu_cores=2,
             cooler_included="Not Included", has_unlocked_multiplier=True, lithography_nm=4),

        dict(name="AMD Ryzen 9 9950X", brand="AMD", socket_id=am5.id,
             architecture="Zen 5", series="Ryzen 9000",
             cores=16, threads=32, base_clock_ghz=4.3, boost_clock_ghz=5.7,
             tdp_watts=170, max_tdp_watts=200, memory_type="DDR5",
             max_memory_speed_mhz=6400, memory_channels=2, pcie_gen=5,
             integrated_graphics=True, igpu_model="AMD Radeon Graphics", igpu_cores=2,
             cooler_included="Not Included", has_unlocked_multiplier=True, lithography_nm=4,
             msrp_usd=649),

        dict(name="AMD Ryzen 9 9900X3D", brand="AMD", socket_id=am5.id,
             architecture="Zen 5", series="Ryzen 9000",
             cores=12, threads=24, base_clock_ghz=4.4, boost_clock_ghz=5.5,
             tdp_watts=120, max_tdp_watts=162, memory_type="DDR5",
             max_memory_speed_mhz=6400, memory_channels=2, pcie_gen=5,
             integrated_graphics=True, igpu_model="AMD Radeon Graphics", igpu_cores=2,
             cooler_included="Not Included", has_unlocked_multiplier=True, lithography_nm=4),

        dict(name="AMD Ryzen 9 9900X", brand="AMD", socket_id=am5.id,
             architecture="Zen 5", series="Ryzen 9000",
             cores=12, threads=24, base_clock_ghz=4.4, boost_clock_ghz=5.6,
             tdp_watts=120, max_tdp_watts=162, memory_type="DDR5",
             max_memory_speed_mhz=6400, memory_channels=2, pcie_gen=5,
             integrated_graphics=True, igpu_model="AMD Radeon Graphics", igpu_cores=2,
             cooler_included="Not Included", has_unlocked_multiplier=True, lithography_nm=4,
             msrp_usd=449),

        dict(name="AMD Ryzen 7 9850X3D", brand="AMD", socket_id=am5.id,
             architecture="Zen 5", series="Ryzen 9000",
             cores=8, threads=16, base_clock_ghz=4.7, boost_clock_ghz=5.6,
             tdp_watts=120, max_tdp_watts=162, memory_type="DDR5",
             max_memory_speed_mhz=6400, memory_channels=2, pcie_gen=5,
             integrated_graphics=True, igpu_model="AMD Radeon Graphics", igpu_cores=2,
             cooler_included="Not Included", has_unlocked_multiplier=True, lithography_nm=4),

        dict(name="AMD Ryzen 7 9800X3D", brand="AMD", socket_id=am5.id,
             architecture="Zen 5", series="Ryzen 9000",
             cores=8, threads=16, base_clock_ghz=4.7, boost_clock_ghz=5.2,
             tdp_watts=120, max_tdp_watts=162, memory_type="DDR5",
             max_memory_speed_mhz=6400, memory_channels=2, pcie_gen=5,
             integrated_graphics=True, igpu_model="AMD Radeon Graphics", igpu_cores=2,
             cooler_included="Not Included", has_unlocked_multiplier=True, lithography_nm=4,
             msrp_usd=479),

        dict(name="AMD Ryzen 7 9700X", brand="AMD", socket_id=am5.id,
             architecture="Zen 5", series="Ryzen 9000",
             cores=8, threads=16, base_clock_ghz=3.8, boost_clock_ghz=5.5,
             tdp_watts=65, max_tdp_watts=88, memory_type="DDR5",
             max_memory_speed_mhz=6400, memory_channels=2, pcie_gen=5,
             integrated_graphics=True, igpu_model="AMD Radeon Graphics", igpu_cores=2,
             cooler_included="Not Included", has_unlocked_multiplier=True, lithography_nm=4,
             msrp_usd=329),

        dict(name="AMD Ryzen 7 9700F", brand="AMD", socket_id=am5.id,
             architecture="Zen 5", series="Ryzen 9000",
             cores=8, threads=16, base_clock_ghz=3.8, boost_clock_ghz=5.5,
             tdp_watts=65, max_tdp_watts=88, memory_type="DDR5",
             max_memory_speed_mhz=6400, memory_channels=2, pcie_gen=5,
             integrated_graphics=False,
             cooler_included="Not Included", has_unlocked_multiplier=True, lithography_nm=4),

        dict(name="AMD Ryzen 5 9600X", brand="AMD", socket_id=am5.id,
             architecture="Zen 5", series="Ryzen 9000",
             cores=6, threads=12, base_clock_ghz=3.9, boost_clock_ghz=5.4,
             tdp_watts=65, max_tdp_watts=88, memory_type="DDR5",
             max_memory_speed_mhz=6400, memory_channels=2, pcie_gen=5,
             integrated_graphics=True, igpu_model="AMD Radeon Graphics", igpu_cores=2,
             cooler_included="Not Included", has_unlocked_multiplier=True, lithography_nm=4,
             msrp_usd=279),

        dict(name="AMD Ryzen 5 9600", brand="AMD", socket_id=am5.id,
             architecture="Zen 5", series="Ryzen 9000",
             cores=6, threads=12, base_clock_ghz=3.8, boost_clock_ghz=5.2,
             tdp_watts=65, max_tdp_watts=88, memory_type="DDR5",
             max_memory_speed_mhz=6400, memory_channels=2, pcie_gen=5,
             integrated_graphics=True, igpu_model="AMD Radeon Graphics", igpu_cores=2,
             cooler_included="AMD Wraith Stealth", has_unlocked_multiplier=True, lithography_nm=4),

        dict(name="AMD Ryzen 5 9500F", brand="AMD", socket_id=am5.id,
             architecture="Zen 5", series="Ryzen 9000",
             cores=6, threads=12, base_clock_ghz=3.8, boost_clock_ghz=5.0,
             tdp_watts=65, max_tdp_watts=88, memory_type="DDR5",
             max_memory_speed_mhz=6400, memory_channels=2, pcie_gen=5,
             integrated_graphics=False,
             cooler_included="AMD Wraith Stealth", has_unlocked_multiplier=True, lithography_nm=4),
    ])

    # ── Ryzen 8000-series (AM5 / Phoenix — iGPU-focused) ────────────────
    _add([
        dict(name="AMD Ryzen 7 8700G", brand="AMD", socket_id=am5.id,
             architecture="Zen 4", series="Ryzen 8000",
             cores=8, threads=16, base_clock_ghz=4.2, boost_clock_ghz=5.1,
             tdp_watts=65, max_tdp_watts=88, memory_type="DDR5",
             max_memory_speed_mhz=5200, memory_channels=2, pcie_gen=4,
             integrated_graphics=True, igpu_model="AMD Radeon 780M", igpu_cores=12,
             cooler_included="AMD Wraith Spire", has_unlocked_multiplier=True, lithography_nm=4,
             msrp_usd=329),

        dict(name="AMD Ryzen 7 8700F", brand="AMD", socket_id=am5.id,
             architecture="Zen 4", series="Ryzen 8000",
             cores=8, threads=16, base_clock_ghz=4.1, boost_clock_ghz=5.0,
             tdp_watts=65, max_tdp_watts=88, memory_type="DDR5",
             max_memory_speed_mhz=5200, memory_channels=2, pcie_gen=4,
             integrated_graphics=False,
             cooler_included="AMD Wraith Spire", has_unlocked_multiplier=True, lithography_nm=4),

        dict(name="AMD Ryzen 5 8600G", brand="AMD", socket_id=am5.id,
             architecture="Zen 4", series="Ryzen 8000",
             cores=6, threads=12, base_clock_ghz=4.3, boost_clock_ghz=5.0,
             tdp_watts=65, max_tdp_watts=88, memory_type="DDR5",
             max_memory_speed_mhz=5200, memory_channels=2, pcie_gen=4,
             integrated_graphics=True, igpu_model="AMD Radeon 760M", igpu_cores=8,
             cooler_included="AMD Wraith Stealth", has_unlocked_multiplier=True, lithography_nm=4,
             msrp_usd=229),

        dict(name="AMD Ryzen 5 8500G", brand="AMD", socket_id=am5.id,
             architecture="Zen 4", series="Ryzen 8000",
             cores=6, threads=12, base_clock_ghz=3.5, boost_clock_ghz=5.0,
             tdp_watts=65, max_tdp_watts=88, memory_type="DDR5",
             max_memory_speed_mhz=5200, memory_channels=2, pcie_gen=4,
             integrated_graphics=True, igpu_model="AMD Radeon 740M", igpu_cores=4,
             cooler_included=None, has_unlocked_multiplier=True, lithography_nm=4),

        dict(name="AMD Ryzen 5 8400F", brand="AMD", socket_id=am5.id,
             architecture="Zen 4", series="Ryzen 8000",
             cores=6, threads=12, base_clock_ghz=4.2, boost_clock_ghz=4.7,
             tdp_watts=65, max_tdp_watts=88, memory_type="DDR5",
             max_memory_speed_mhz=5200, memory_channels=2, pcie_gen=4,
             integrated_graphics=False,
             cooler_included=None, has_unlocked_multiplier=False, lithography_nm=4),

        dict(name="AMD Ryzen 3 8300G", brand="AMD", socket_id=am5.id,
             architecture="Zen 4", series="Ryzen 8000",
             cores=4, threads=8, base_clock_ghz=3.4, boost_clock_ghz=4.9,
             tdp_watts=65, max_tdp_watts=88, memory_type="DDR5",
             max_memory_speed_mhz=5200, memory_channels=2, pcie_gen=4,
             integrated_graphics=True, igpu_model="AMD Radeon 740M", igpu_cores=4,
             cooler_included=None, has_unlocked_multiplier=True, lithography_nm=4),
    ])

    # ── Ryzen 7000-series (AM5 / Raphael / Zen 4) ───────────────────────
    _add([
        dict(name="AMD Ryzen 9 7950X3D", brand="AMD", socket_id=am5.id,
             architecture="Zen 4", series="Ryzen 7000",
             cores=16, threads=32, base_clock_ghz=4.2, boost_clock_ghz=5.7,
             tdp_watts=120, max_tdp_watts=162, memory_type="DDR5",
             max_memory_speed_mhz=5200, memory_channels=2, pcie_gen=5,
             integrated_graphics=True, igpu_model="AMD Radeon Graphics", igpu_cores=2,
             cooler_included="Not Included", has_unlocked_multiplier=True, lithography_nm=5,
             msrp_usd=699),

        dict(name="AMD Ryzen 9 7950X", brand="AMD", socket_id=am5.id,
             architecture="Zen 4", series="Ryzen 7000",
             cores=16, threads=32, base_clock_ghz=4.5, boost_clock_ghz=5.7,
             tdp_watts=170, max_tdp_watts=230, memory_type="DDR5",
             max_memory_speed_mhz=5200, memory_channels=2, pcie_gen=5,
             integrated_graphics=True, igpu_model="AMD Radeon Graphics", igpu_cores=2,
             cooler_included="Not Included", has_unlocked_multiplier=True, lithography_nm=5,
             msrp_usd=699),

        dict(name="AMD Ryzen 9 7900X3D", brand="AMD", socket_id=am5.id,
             architecture="Zen 4", series="Ryzen 7000",
             cores=12, threads=24, base_clock_ghz=4.4, boost_clock_ghz=5.6,
             tdp_watts=120, max_tdp_watts=162, memory_type="DDR5",
             max_memory_speed_mhz=5200, memory_channels=2, pcie_gen=5,
             integrated_graphics=True, igpu_model="AMD Radeon Graphics", igpu_cores=2,
             cooler_included="Not Included", has_unlocked_multiplier=True, lithography_nm=5,
             msrp_usd=449),

        dict(name="AMD Ryzen 9 7900X", brand="AMD", socket_id=am5.id,
             architecture="Zen 4", series="Ryzen 7000",
             cores=12, threads=24, base_clock_ghz=4.7, boost_clock_ghz=5.6,
             tdp_watts=170, max_tdp_watts=230, memory_type="DDR5",
             max_memory_speed_mhz=5200, memory_channels=2, pcie_gen=5,
             integrated_graphics=True, igpu_model="AMD Radeon Graphics", igpu_cores=2,
             cooler_included="Not Included", has_unlocked_multiplier=True, lithography_nm=5,
             msrp_usd=449),

        dict(name="AMD Ryzen 9 7900", brand="AMD", socket_id=am5.id,
             architecture="Zen 4", series="Ryzen 7000",
             cores=12, threads=24, base_clock_ghz=3.7, boost_clock_ghz=5.4,
             tdp_watts=65, max_tdp_watts=88, memory_type="DDR5",
             max_memory_speed_mhz=5200, memory_channels=2, pcie_gen=5,
             integrated_graphics=True, igpu_model="AMD Radeon Graphics", igpu_cores=2,
             cooler_included="AMD Wraith Prism", has_unlocked_multiplier=True, lithography_nm=5,
             msrp_usd=429),

        dict(name="AMD Ryzen 7 7800X3D", brand="AMD", socket_id=am5.id,
             architecture="Zen 4", series="Ryzen 7000",
             cores=8, threads=16, base_clock_ghz=4.5, boost_clock_ghz=5.0,
             tdp_watts=120, max_tdp_watts=162, memory_type="DDR5",
             max_memory_speed_mhz=5200, memory_channels=2, pcie_gen=5,
             integrated_graphics=True, igpu_model="AMD Radeon Graphics", igpu_cores=2,
             cooler_included="Not Included", has_unlocked_multiplier=False, lithography_nm=5,
             msrp_usd=449),

        dict(name="AMD Ryzen 7 7700X", brand="AMD", socket_id=am5.id,
             architecture="Zen 4", series="Ryzen 7000",
             cores=8, threads=16, base_clock_ghz=4.5, boost_clock_ghz=5.4,
             tdp_watts=105, max_tdp_watts=142, memory_type="DDR5",
             max_memory_speed_mhz=5200, memory_channels=2, pcie_gen=5,
             integrated_graphics=True, igpu_model="AMD Radeon Graphics", igpu_cores=2,
             cooler_included="Not Included", has_unlocked_multiplier=True, lithography_nm=5,
             msrp_usd=299),

        dict(name="AMD Ryzen 7 7700", brand="AMD", socket_id=am5.id,
             architecture="Zen 4", series="Ryzen 7000",
             cores=8, threads=16, base_clock_ghz=3.8, boost_clock_ghz=5.3,
             tdp_watts=65, max_tdp_watts=88, memory_type="DDR5",
             max_memory_speed_mhz=5200, memory_channels=2, pcie_gen=5,
             integrated_graphics=True, igpu_model="AMD Radeon Graphics", igpu_cores=2,
             cooler_included="AMD Wraith Prism", has_unlocked_multiplier=True, lithography_nm=5,
             msrp_usd=329),

        dict(name="AMD Ryzen 5 7600X", brand="AMD", socket_id=am5.id,
             architecture="Zen 4", series="Ryzen 7000",
             cores=6, threads=12, base_clock_ghz=4.7, boost_clock_ghz=5.3,
             tdp_watts=105, max_tdp_watts=142, memory_type="DDR5",
             max_memory_speed_mhz=5200, memory_channels=2, pcie_gen=5,
             integrated_graphics=True, igpu_model="AMD Radeon Graphics", igpu_cores=2,
             cooler_included="Not Included", has_unlocked_multiplier=True, lithography_nm=5,
             msrp_usd=229),

        dict(name="AMD Ryzen 5 7600", brand="AMD", socket_id=am5.id,
             architecture="Zen 4", series="Ryzen 7000",
             cores=6, threads=12, base_clock_ghz=3.8, boost_clock_ghz=5.1,
             tdp_watts=65, max_tdp_watts=88, memory_type="DDR5",
             max_memory_speed_mhz=5200, memory_channels=2, pcie_gen=5,
             integrated_graphics=True, igpu_model="AMD Radeon Graphics", igpu_cores=2,
             cooler_included="AMD Wraith Stealth", has_unlocked_multiplier=True, lithography_nm=5,
             msrp_usd=229),

        dict(name="AMD Ryzen 5 7500F", brand="AMD", socket_id=am5.id,
             architecture="Zen 4", series="Ryzen 7000",
             cores=6, threads=12, base_clock_ghz=3.7, boost_clock_ghz=5.0,
             tdp_watts=65, max_tdp_watts=88, memory_type="DDR5",
             max_memory_speed_mhz=5200, memory_channels=2, pcie_gen=5,
             integrated_graphics=False,
             cooler_included="AMD Wraith Stealth", has_unlocked_multiplier=False, lithography_nm=5,
             msrp_usd=179),
    ])

    # ── Ryzen 5000-series (AM4 / Zen 3) ─────────────────────────────────
    _add([
        dict(name="AMD Ryzen 9 5950X", brand="AMD", socket_id=am4.id,
             architecture="Zen 3", series="Ryzen 5000",
             cores=16, threads=32, base_clock_ghz=3.4, boost_clock_ghz=4.9,
             tdp_watts=105, max_tdp_watts=142, memory_type="DDR4",
             max_memory_speed_mhz=3200, memory_channels=2, pcie_gen=4,
             integrated_graphics=False,
             cooler_included="Not Included", has_unlocked_multiplier=True, lithography_nm=7,
             msrp_usd=799),

        dict(name="AMD Ryzen 9 5900XT", brand="AMD", socket_id=am4.id,
             architecture="Zen 3", series="Ryzen 5000",
             cores=16, threads=32, base_clock_ghz=3.3, boost_clock_ghz=4.8,
             tdp_watts=105, max_tdp_watts=142, memory_type="DDR4",
             max_memory_speed_mhz=3200, memory_channels=2, pcie_gen=4,
             integrated_graphics=False,
             cooler_included="Not Included", has_unlocked_multiplier=True, lithography_nm=7),

        dict(name="AMD Ryzen 9 5900X", brand="AMD", socket_id=am4.id,
             architecture="Zen 3", series="Ryzen 5000",
             cores=12, threads=24, base_clock_ghz=3.7, boost_clock_ghz=4.8,
             tdp_watts=105, max_tdp_watts=142, memory_type="DDR4",
             max_memory_speed_mhz=3200, memory_channels=2, pcie_gen=4,
             integrated_graphics=False,
             cooler_included="Not Included", has_unlocked_multiplier=True, lithography_nm=7,
             msrp_usd=549),

        dict(name="AMD Ryzen 7 5800X3D", brand="AMD", socket_id=am4.id,
             architecture="Zen 3", series="Ryzen 5000",
             cores=8, threads=16, base_clock_ghz=3.4, boost_clock_ghz=4.5,
             tdp_watts=105, max_tdp_watts=142, memory_type="DDR4",
             max_memory_speed_mhz=3200, memory_channels=2, pcie_gen=4,
             integrated_graphics=False,
             cooler_included="Not Included", has_unlocked_multiplier=False, lithography_nm=7,
             msrp_usd=449),

        dict(name="AMD Ryzen 7 5800XT", brand="AMD", socket_id=am4.id,
             architecture="Zen 3", series="Ryzen 5000",
             cores=8, threads=16, base_clock_ghz=3.8, boost_clock_ghz=4.8,
             tdp_watts=105, max_tdp_watts=142, memory_type="DDR4",
             max_memory_speed_mhz=3200, memory_channels=2, pcie_gen=4,
             integrated_graphics=False,
             cooler_included=None, has_unlocked_multiplier=True, lithography_nm=7),

        dict(name="AMD Ryzen 7 5800X", brand="AMD", socket_id=am4.id,
             architecture="Zen 3", series="Ryzen 5000",
             cores=8, threads=16, base_clock_ghz=3.8, boost_clock_ghz=4.7,
             tdp_watts=105, max_tdp_watts=142, memory_type="DDR4",
             max_memory_speed_mhz=3200, memory_channels=2, pcie_gen=4,
             integrated_graphics=False,
             cooler_included="Not Included", has_unlocked_multiplier=True, lithography_nm=7,
             msrp_usd=449),

        dict(name="AMD Ryzen 7 5700X3D", brand="AMD", socket_id=am4.id,
             architecture="Zen 3", series="Ryzen 5000",
             cores=8, threads=16, base_clock_ghz=3.0, boost_clock_ghz=4.1,
             tdp_watts=105, max_tdp_watts=142, memory_type="DDR4",
             max_memory_speed_mhz=3200, memory_channels=2, pcie_gen=4,
             integrated_graphics=False,
             cooler_included="Not Included", has_unlocked_multiplier=False, lithography_nm=7),

        dict(name="AMD Ryzen 7 5700X", brand="AMD", socket_id=am4.id,
             architecture="Zen 3", series="Ryzen 5000",
             cores=8, threads=16, base_clock_ghz=3.4, boost_clock_ghz=4.6,
             tdp_watts=65, max_tdp_watts=88, memory_type="DDR4",
             max_memory_speed_mhz=3200, memory_channels=2, pcie_gen=4,
             integrated_graphics=False,
             cooler_included="Not Included", has_unlocked_multiplier=True, lithography_nm=7,
             msrp_usd=299),

        dict(name="AMD Ryzen 7 5700G", brand="AMD", socket_id=am4.id,
             architecture="Zen 3", series="Ryzen 5000",
             cores=8, threads=16, base_clock_ghz=3.8, boost_clock_ghz=4.6,
             tdp_watts=65, max_tdp_watts=88, memory_type="DDR4",
             max_memory_speed_mhz=3200, memory_channels=2, pcie_gen=3,
             integrated_graphics=True, igpu_model="AMD Radeon Graphics", igpu_cores=8,
             cooler_included="AMD Wraith Stealth", has_unlocked_multiplier=True, lithography_nm=7,
             msrp_usd=329),

        dict(name="AMD Ryzen 7 5700", brand="AMD", socket_id=am4.id,
             architecture="Zen 3", series="Ryzen 5000",
             cores=8, threads=16, base_clock_ghz=3.7, boost_clock_ghz=4.6,
             tdp_watts=65, max_tdp_watts=88, memory_type="DDR4",
             max_memory_speed_mhz=3200, memory_channels=2, pcie_gen=4,
             integrated_graphics=False,
             cooler_included="AMD Wraith Stealth", has_unlocked_multiplier=False, lithography_nm=7),

        dict(name="AMD Ryzen 5 5600X3D", brand="AMD", socket_id=am4.id,
             architecture="Zen 3", series="Ryzen 5000",
             cores=6, threads=12, base_clock_ghz=3.3, boost_clock_ghz=4.4,
             tdp_watts=105, max_tdp_watts=142, memory_type="DDR4",
             max_memory_speed_mhz=3200, memory_channels=2, pcie_gen=4,
             integrated_graphics=False,
             cooler_included="Not Included", has_unlocked_multiplier=False, lithography_nm=7),

        dict(name="AMD Ryzen 5 5600X", brand="AMD", socket_id=am4.id,
             architecture="Zen 3", series="Ryzen 5000",
             cores=6, threads=12, base_clock_ghz=3.7, boost_clock_ghz=4.6,
             tdp_watts=65, max_tdp_watts=88, memory_type="DDR4",
             max_memory_speed_mhz=3200, memory_channels=2, pcie_gen=4,
             integrated_graphics=False,
             cooler_included="AMD Wraith Stealth", has_unlocked_multiplier=True, lithography_nm=7,
             msrp_usd=299),

        dict(name="AMD Ryzen 5 5600XT", brand="AMD", socket_id=am4.id,
             architecture="Zen 3", series="Ryzen 5000",
             cores=6, threads=12, base_clock_ghz=3.7, boost_clock_ghz=4.7,
             tdp_watts=65, max_tdp_watts=88, memory_type="DDR4",
             max_memory_speed_mhz=3200, memory_channels=2, pcie_gen=4,
             integrated_graphics=False,
             cooler_included="AMD Wraith Stealth", has_unlocked_multiplier=True, lithography_nm=7),

        dict(name="AMD Ryzen 5 5600G", brand="AMD", socket_id=am4.id,
             architecture="Zen 3", series="Ryzen 5000",
             cores=6, threads=12, base_clock_ghz=3.9, boost_clock_ghz=4.4,
             tdp_watts=65, max_tdp_watts=88, memory_type="DDR4",
             max_memory_speed_mhz=3200, memory_channels=2, pcie_gen=3,
             integrated_graphics=True, igpu_model="AMD Radeon Graphics", igpu_cores=7,
             cooler_included="AMD Wraith Stealth", has_unlocked_multiplier=True, lithography_nm=7,
             msrp_usd=199),

        dict(name="AMD Ryzen 5 5600", brand="AMD", socket_id=am4.id,
             architecture="Zen 3", series="Ryzen 5000",
             cores=6, threads=12, base_clock_ghz=3.5, boost_clock_ghz=4.4,
             tdp_watts=65, max_tdp_watts=88, memory_type="DDR4",
             max_memory_speed_mhz=3200, memory_channels=2, pcie_gen=4,
             integrated_graphics=False,
             cooler_included="AMD Wraith Stealth", has_unlocked_multiplier=False, lithography_nm=7,
             msrp_usd=199),

        dict(name="AMD Ryzen 5 5500X3D", brand="AMD", socket_id=am4.id,
             architecture="Zen 3", series="Ryzen 5000",
             cores=6, threads=12, base_clock_ghz=3.0, boost_clock_ghz=4.0,
             tdp_watts=105, max_tdp_watts=142, memory_type="DDR4",
             max_memory_speed_mhz=3200, memory_channels=2, pcie_gen=4,
             integrated_graphics=False,
             cooler_included="Not Included", has_unlocked_multiplier=False, lithography_nm=7),

        dict(name="AMD Ryzen 5 5500GT", brand="AMD", socket_id=am4.id,
             architecture="Zen 3", series="Ryzen 5000",
             cores=6, threads=12, base_clock_ghz=3.6, boost_clock_ghz=4.4,
             tdp_watts=65, max_tdp_watts=88, memory_type="DDR4",
             max_memory_speed_mhz=3200, memory_channels=2, pcie_gen=3,
             integrated_graphics=True, igpu_model="AMD Radeon Graphics", igpu_cores=7,
             cooler_included="AMD Wraith Stealth", has_unlocked_multiplier=False, lithography_nm=7),

        dict(name="AMD Ryzen 5 5500", brand="AMD", socket_id=am4.id,
             architecture="Zen 3", series="Ryzen 5000",
             cores=6, threads=12, base_clock_ghz=3.6, boost_clock_ghz=4.2,
             tdp_watts=65, max_tdp_watts=88, memory_type="DDR4",
             max_memory_speed_mhz=3200, memory_channels=2, pcie_gen=3,
             integrated_graphics=False,
             cooler_included="AMD Wraith Stealth", has_unlocked_multiplier=False, lithography_nm=7,
             msrp_usd=159),

        dict(name="AMD Ryzen 3 5300G", brand="AMD", socket_id=am4.id,
             architecture="Zen 3", series="Ryzen 5000",
             cores=4, threads=8, base_clock_ghz=4.0, boost_clock_ghz=4.2,
             tdp_watts=65, max_tdp_watts=88, memory_type="DDR4",
             max_memory_speed_mhz=3200, memory_channels=2, pcie_gen=3,
             integrated_graphics=True, igpu_model="AMD Radeon Graphics", igpu_cores=6,
             cooler_included=None, has_unlocked_multiplier=True, lithography_nm=7),
    ])

    # ── Ryzen 4000-series (AM4 / Renoir / OEM) ──────────────────────────
    _add([
        dict(name="AMD Ryzen 7 4700GE", brand="AMD", socket_id=am4.id,
             architecture="Zen 2", series="Ryzen 4000",
             cores=8, threads=16, base_clock_ghz=3.1, boost_clock_ghz=4.3,
             tdp_watts=35, max_tdp_watts=54, memory_type="DDR4",
             max_memory_speed_mhz=3200, memory_channels=2, pcie_gen=3,
             integrated_graphics=True, igpu_model="AMD Radeon Graphics", igpu_cores=8,
             cooler_included=None, has_unlocked_multiplier=False, lithography_nm=7),

        dict(name="AMD Ryzen 7 4700G", brand="AMD", socket_id=am4.id,
             architecture="Zen 2", series="Ryzen 4000",
             cores=8, threads=16, base_clock_ghz=3.6, boost_clock_ghz=4.4,
             tdp_watts=65, max_tdp_watts=88, memory_type="DDR4",
             max_memory_speed_mhz=3200, memory_channels=2, pcie_gen=3,
             integrated_graphics=True, igpu_model="AMD Radeon Graphics", igpu_cores=8,
             cooler_included=None, has_unlocked_multiplier=False, lithography_nm=7),

        dict(name="AMD Ryzen 5 4600GE", brand="AMD", socket_id=am4.id,
             architecture="Zen 2", series="Ryzen 4000",
             cores=6, threads=12, base_clock_ghz=3.3, boost_clock_ghz=4.2,
             tdp_watts=35, max_tdp_watts=54, memory_type="DDR4",
             max_memory_speed_mhz=3200, memory_channels=2, pcie_gen=3,
             integrated_graphics=True, igpu_model="AMD Radeon Graphics", igpu_cores=7,
             cooler_included=None, has_unlocked_multiplier=False, lithography_nm=7),

        dict(name="AMD Ryzen 5 4600G", brand="AMD", socket_id=am4.id,
             architecture="Zen 2", series="Ryzen 4000",
             cores=6, threads=12, base_clock_ghz=3.7, boost_clock_ghz=4.2,
             tdp_watts=65, max_tdp_watts=88, memory_type="DDR4",
             max_memory_speed_mhz=3200, memory_channels=2, pcie_gen=3,
             integrated_graphics=True, igpu_model="AMD Radeon Graphics", igpu_cores=7,
             cooler_included=None, has_unlocked_multiplier=False, lithography_nm=7),

        dict(name="AMD Ryzen 3 4300GE", brand="AMD", socket_id=am4.id,
             architecture="Zen 2", series="Ryzen 4000",
             cores=4, threads=8, base_clock_ghz=3.5, boost_clock_ghz=4.0,
             tdp_watts=35, max_tdp_watts=54, memory_type="DDR4",
             max_memory_speed_mhz=3200, memory_channels=2, pcie_gen=3,
             integrated_graphics=True, igpu_model="AMD Radeon Graphics", igpu_cores=6,
             cooler_included=None, has_unlocked_multiplier=False, lithography_nm=7),
    ])

    db.session.commit()
