"""Seed 02 — Intel CPUs: Core Gen 8 through Core Ultra 200 series.

All specifications sourced from Intel ARK database and public data.
Socket mapping:
  LGA1151 → Gen 8, 9
  LGA1200 → Gen 10, 11
  LGA1700 → Gen 12, 13, 14
  LGA1851 → Core Ultra 200 (Arrow Lake)
"""

from models import db, CPU, CpuSocket


def _socket(name):
    return CpuSocket.query.filter_by(name=name).first()


def _add(cpus):
    for c in cpus:
        if not CPU.query.filter_by(name=c["name"]).first():
            db.session.add(CPU(**c))
    db.session.flush()


def seed():
    lga1151 = _socket("LGA1151")
    lga1200 = _socket("LGA1200")
    lga1700 = _socket("LGA1700")
    lga1851 = _socket("LGA1851")

    # ── Gen 8 (Coffee Lake, LGA1151) ─────────────────────────────────────
    _add([
        dict(name="Intel Core i9-8950HK", brand="Intel", socket_id=lga1151.id,
             architecture="Coffee Lake", series="Core Gen 8",
             cores=6, threads=12, base_clock_ghz=2.9, boost_clock_ghz=4.8,
             tdp_watts=45, memory_type="DDR4", max_memory_speed_mhz=2666, pcie_gen=3,
             integrated_graphics=True, igpu_model="Intel UHD Graphics 630", igpu_cores=24,
             has_unlocked_multiplier=True, lithography_nm=14),

        dict(name="Intel Core i7-8700K", brand="Intel", socket_id=lga1151.id,
             architecture="Coffee Lake", series="Core Gen 8",
             cores=6, threads=12, base_clock_ghz=3.7, boost_clock_ghz=4.7,
             tdp_watts=95, memory_type="DDR4", max_memory_speed_mhz=2666,
             memory_channels=2, pcie_gen=3,
             integrated_graphics=True, igpu_model="Intel UHD Graphics 630", igpu_cores=24,
             cooler_included="Not Included", has_unlocked_multiplier=True, lithography_nm=14,
             msrp_usd=359),

        dict(name="Intel Core i7-8700", brand="Intel", socket_id=lga1151.id,
             architecture="Coffee Lake", series="Core Gen 8",
             cores=6, threads=12, base_clock_ghz=3.2, boost_clock_ghz=4.6,
             tdp_watts=65, memory_type="DDR4", max_memory_speed_mhz=2666,
             memory_channels=2, pcie_gen=3,
             integrated_graphics=True, igpu_model="Intel UHD Graphics 630", igpu_cores=24,
             cooler_included="Intel Stock Cooler", has_unlocked_multiplier=False, lithography_nm=14),

        dict(name="Intel Core i5-8600K", brand="Intel", socket_id=lga1151.id,
             architecture="Coffee Lake", series="Core Gen 8",
             cores=6, threads=6, base_clock_ghz=3.6, boost_clock_ghz=4.3,
             tdp_watts=95, memory_type="DDR4", max_memory_speed_mhz=2666,
             memory_channels=2, pcie_gen=3,
             integrated_graphics=True, igpu_model="Intel UHD Graphics 630", igpu_cores=24,
             cooler_included="Not Included", has_unlocked_multiplier=True, lithography_nm=14,
             msrp_usd=257),

        dict(name="Intel Core i5-8600", brand="Intel", socket_id=lga1151.id,
             architecture="Coffee Lake", series="Core Gen 8",
             cores=6, threads=6, base_clock_ghz=3.1, boost_clock_ghz=4.3,
             tdp_watts=65, memory_type="DDR4", max_memory_speed_mhz=2666,
             memory_channels=2, pcie_gen=3,
             integrated_graphics=True, igpu_model="Intel UHD Graphics 630", igpu_cores=24,
             cooler_included="Intel Stock Cooler", has_unlocked_multiplier=False, lithography_nm=14),

        dict(name="Intel Core i5-8500", brand="Intel", socket_id=lga1151.id,
             architecture="Coffee Lake", series="Core Gen 8",
             cores=6, threads=6, base_clock_ghz=3.0, boost_clock_ghz=4.1,
             tdp_watts=65, memory_type="DDR4", max_memory_speed_mhz=2666,
             memory_channels=2, pcie_gen=3,
             integrated_graphics=True, igpu_model="Intel UHD Graphics 630", igpu_cores=24,
             cooler_included="Intel Stock Cooler", has_unlocked_multiplier=False, lithography_nm=14),

        dict(name="Intel Core i5-8400", brand="Intel", socket_id=lga1151.id,
             architecture="Coffee Lake", series="Core Gen 8",
             cores=6, threads=6, base_clock_ghz=2.8, boost_clock_ghz=4.0,
             tdp_watts=65, memory_type="DDR4", max_memory_speed_mhz=2666,
             memory_channels=2, pcie_gen=3,
             integrated_graphics=True, igpu_model="Intel UHD Graphics 630", igpu_cores=24,
             cooler_included="Intel Stock Cooler", has_unlocked_multiplier=False, lithography_nm=14,
             msrp_usd=182),

        dict(name="Intel Core i3-8350K", brand="Intel", socket_id=lga1151.id,
             architecture="Coffee Lake", series="Core Gen 8",
             cores=4, threads=4, base_clock_ghz=4.0, boost_clock_ghz=4.0,
             tdp_watts=91, memory_type="DDR4", max_memory_speed_mhz=2400,
             memory_channels=2, pcie_gen=3,
             integrated_graphics=True, igpu_model="Intel UHD Graphics 630", igpu_cores=24,
             cooler_included="Not Included", has_unlocked_multiplier=True, lithography_nm=14),

        dict(name="Intel Core i3-8300", brand="Intel", socket_id=lga1151.id,
             architecture="Coffee Lake", series="Core Gen 8",
             cores=4, threads=4, base_clock_ghz=3.7, boost_clock_ghz=3.7,
             tdp_watts=62, memory_type="DDR4", max_memory_speed_mhz=2400,
             memory_channels=2, pcie_gen=3,
             integrated_graphics=True, igpu_model="Intel UHD Graphics 630", igpu_cores=24,
             cooler_included="Intel Stock Cooler", has_unlocked_multiplier=False, lithography_nm=14),

        dict(name="Intel Core i3-8100", brand="Intel", socket_id=lga1151.id,
             architecture="Coffee Lake", series="Core Gen 8",
             cores=4, threads=4, base_clock_ghz=3.6, boost_clock_ghz=3.6,
             tdp_watts=65, memory_type="DDR4", max_memory_speed_mhz=2400,
             memory_channels=2, pcie_gen=3,
             integrated_graphics=True, igpu_model="Intel UHD Graphics 630", igpu_cores=24,
             cooler_included="Intel Stock Cooler", has_unlocked_multiplier=False, lithography_nm=14,
             msrp_usd=117),
    ])

    # ── Gen 9 (Coffee Lake Refresh, LGA1151) ─────────────────────────────
    _add([
        dict(name="Intel Core i9-9900KS", brand="Intel", socket_id=lga1151.id,
             architecture="Coffee Lake", series="Core Gen 9",
             cores=8, threads=16, base_clock_ghz=4.0, boost_clock_ghz=5.0,
             tdp_watts=127, memory_type="DDR4", max_memory_speed_mhz=2666,
             memory_channels=2, pcie_gen=3,
             integrated_graphics=True, igpu_model="Intel UHD Graphics 630", igpu_cores=24,
             cooler_included="Not Included", has_unlocked_multiplier=True, lithography_nm=14,
             msrp_usd=513),

        dict(name="Intel Core i9-9900K", brand="Intel", socket_id=lga1151.id,
             architecture="Coffee Lake", series="Core Gen 9",
             cores=8, threads=16, base_clock_ghz=3.6, boost_clock_ghz=5.0,
             tdp_watts=95, memory_type="DDR4", max_memory_speed_mhz=2666,
             memory_channels=2, pcie_gen=3,
             integrated_graphics=True, igpu_model="Intel UHD Graphics 630", igpu_cores=24,
             cooler_included="Not Included", has_unlocked_multiplier=True, lithography_nm=14,
             msrp_usd=488),

        dict(name="Intel Core i9-9900KF", brand="Intel", socket_id=lga1151.id,
             architecture="Coffee Lake", series="Core Gen 9",
             cores=8, threads=16, base_clock_ghz=3.6, boost_clock_ghz=5.0,
             tdp_watts=95, memory_type="DDR4", max_memory_speed_mhz=2666,
             memory_channels=2, pcie_gen=3,
             integrated_graphics=False,
             cooler_included="Not Included", has_unlocked_multiplier=True, lithography_nm=14),

        dict(name="Intel Core i9-9900", brand="Intel", socket_id=lga1151.id,
             architecture="Coffee Lake", series="Core Gen 9",
             cores=8, threads=16, base_clock_ghz=3.1, boost_clock_ghz=5.0,
             tdp_watts=65, memory_type="DDR4", max_memory_speed_mhz=2666,
             memory_channels=2, pcie_gen=3,
             integrated_graphics=True, igpu_model="Intel UHD Graphics 630", igpu_cores=24,
             cooler_included="Intel Stock Cooler", has_unlocked_multiplier=False, lithography_nm=14),

        dict(name="Intel Core i7-9700K", brand="Intel", socket_id=lga1151.id,
             architecture="Coffee Lake", series="Core Gen 9",
             cores=8, threads=8, base_clock_ghz=3.6, boost_clock_ghz=4.9,
             tdp_watts=95, memory_type="DDR4", max_memory_speed_mhz=2666,
             memory_channels=2, pcie_gen=3,
             integrated_graphics=True, igpu_model="Intel UHD Graphics 630", igpu_cores=24,
             cooler_included="Not Included", has_unlocked_multiplier=True, lithography_nm=14,
             msrp_usd=374),

        dict(name="Intel Core i7-9700KF", brand="Intel", socket_id=lga1151.id,
             architecture="Coffee Lake", series="Core Gen 9",
             cores=8, threads=8, base_clock_ghz=3.6, boost_clock_ghz=4.9,
             tdp_watts=95, memory_type="DDR4", max_memory_speed_mhz=2666,
             memory_channels=2, pcie_gen=3,
             integrated_graphics=False,
             cooler_included="Not Included", has_unlocked_multiplier=True, lithography_nm=14),

        dict(name="Intel Core i7-9700", brand="Intel", socket_id=lga1151.id,
             architecture="Coffee Lake", series="Core Gen 9",
             cores=8, threads=8, base_clock_ghz=3.0, boost_clock_ghz=4.7,
             tdp_watts=65, memory_type="DDR4", max_memory_speed_mhz=2666,
             memory_channels=2, pcie_gen=3,
             integrated_graphics=True, igpu_model="Intel UHD Graphics 630", igpu_cores=24,
             cooler_included="Intel Stock Cooler", has_unlocked_multiplier=False, lithography_nm=14),

        dict(name="Intel Core i5-9600K", brand="Intel", socket_id=lga1151.id,
             architecture="Coffee Lake", series="Core Gen 9",
             cores=6, threads=6, base_clock_ghz=3.7, boost_clock_ghz=4.6,
             tdp_watts=95, memory_type="DDR4", max_memory_speed_mhz=2666,
             memory_channels=2, pcie_gen=3,
             integrated_graphics=True, igpu_model="Intel UHD Graphics 630", igpu_cores=24,
             cooler_included="Not Included", has_unlocked_multiplier=True, lithography_nm=14,
             msrp_usd=262),

        dict(name="Intel Core i5-9600KF", brand="Intel", socket_id=lga1151.id,
             architecture="Coffee Lake", series="Core Gen 9",
             cores=6, threads=6, base_clock_ghz=3.7, boost_clock_ghz=4.6,
             tdp_watts=95, memory_type="DDR4", max_memory_speed_mhz=2666,
             memory_channels=2, pcie_gen=3,
             integrated_graphics=False,
             cooler_included="Not Included", has_unlocked_multiplier=True, lithography_nm=14),

        dict(name="Intel Core i5-9600", brand="Intel", socket_id=lga1151.id,
             architecture="Coffee Lake", series="Core Gen 9",
             cores=6, threads=6, base_clock_ghz=3.1, boost_clock_ghz=4.6,
             tdp_watts=65, memory_type="DDR4", max_memory_speed_mhz=2666,
             memory_channels=2, pcie_gen=3,
             integrated_graphics=True, igpu_model="Intel UHD Graphics 630", igpu_cores=24,
             cooler_included="Intel Stock Cooler", has_unlocked_multiplier=False, lithography_nm=14),

        dict(name="Intel Core i5-9500", brand="Intel", socket_id=lga1151.id,
             architecture="Coffee Lake", series="Core Gen 9",
             cores=6, threads=6, base_clock_ghz=3.0, boost_clock_ghz=4.4,
             tdp_watts=65, memory_type="DDR4", max_memory_speed_mhz=2666,
             memory_channels=2, pcie_gen=3,
             integrated_graphics=True, igpu_model="Intel UHD Graphics 630", igpu_cores=24,
             cooler_included="Intel Stock Cooler", has_unlocked_multiplier=False, lithography_nm=14),

        dict(name="Intel Core i5-9400", brand="Intel", socket_id=lga1151.id,
             architecture="Coffee Lake", series="Core Gen 9",
             cores=6, threads=6, base_clock_ghz=2.9, boost_clock_ghz=4.1,
             tdp_watts=65, memory_type="DDR4", max_memory_speed_mhz=2666,
             memory_channels=2, pcie_gen=3,
             integrated_graphics=True, igpu_model="Intel UHD Graphics 630", igpu_cores=24,
             cooler_included="Intel Stock Cooler", has_unlocked_multiplier=False, lithography_nm=14,
             msrp_usd=182),

        dict(name="Intel Core i5-9400F", brand="Intel", socket_id=lga1151.id,
             architecture="Coffee Lake", series="Core Gen 9",
             cores=6, threads=6, base_clock_ghz=2.9, boost_clock_ghz=4.1,
             tdp_watts=65, memory_type="DDR4", max_memory_speed_mhz=2666,
             memory_channels=2, pcie_gen=3,
             integrated_graphics=False,
             cooler_included="Intel Stock Cooler", has_unlocked_multiplier=False, lithography_nm=14,
             msrp_usd=182),

        dict(name="Intel Core i3-9350K", brand="Intel", socket_id=lga1151.id,
             architecture="Coffee Lake", series="Core Gen 9",
             cores=4, threads=4, base_clock_ghz=4.0, boost_clock_ghz=4.6,
             tdp_watts=91, memory_type="DDR4", max_memory_speed_mhz=2400,
             memory_channels=2, pcie_gen=3,
             integrated_graphics=True, igpu_model="Intel UHD Graphics 630", igpu_cores=24,
             cooler_included="Not Included", has_unlocked_multiplier=True, lithography_nm=14),

        dict(name="Intel Core i3-9100", brand="Intel", socket_id=lga1151.id,
             architecture="Coffee Lake", series="Core Gen 9",
             cores=4, threads=4, base_clock_ghz=3.6, boost_clock_ghz=4.2,
             tdp_watts=65, memory_type="DDR4", max_memory_speed_mhz=2400,
             memory_channels=2, pcie_gen=3,
             integrated_graphics=True, igpu_model="Intel UHD Graphics 630", igpu_cores=24,
             cooler_included="Intel Stock Cooler", has_unlocked_multiplier=False, lithography_nm=14,
             msrp_usd=122),

        dict(name="Intel Core i3-9100F", brand="Intel", socket_id=lga1151.id,
             architecture="Coffee Lake", series="Core Gen 9",
             cores=4, threads=4, base_clock_ghz=3.6, boost_clock_ghz=4.2,
             tdp_watts=65, memory_type="DDR4", max_memory_speed_mhz=2400,
             memory_channels=2, pcie_gen=3,
             integrated_graphics=False,
             cooler_included="Intel Stock Cooler", has_unlocked_multiplier=False, lithography_nm=14),
    ])

    # ── Gen 10 (Comet Lake, LGA1200) ─────────────────────────────────────
    _add([
        dict(name="Intel Core i9-10900K", brand="Intel", socket_id=lga1200.id,
             architecture="Comet Lake", series="Core Gen 10",
             cores=10, threads=20, base_clock_ghz=3.7, boost_clock_ghz=5.3,
             tdp_watts=125, memory_type="DDR4", max_memory_speed_mhz=2933,
             memory_channels=2, pcie_gen=3,
             integrated_graphics=True, igpu_model="Intel UHD Graphics 630", igpu_cores=24,
             cooler_included="Not Included", has_unlocked_multiplier=True, lithography_nm=14,
             msrp_usd=488),

        dict(name="Intel Core i9-10900KF", brand="Intel", socket_id=lga1200.id,
             architecture="Comet Lake", series="Core Gen 10",
             cores=10, threads=20, base_clock_ghz=3.7, boost_clock_ghz=5.3,
             tdp_watts=125, memory_type="DDR4", max_memory_speed_mhz=2933,
             memory_channels=2, pcie_gen=3,
             integrated_graphics=False,
             cooler_included="Not Included", has_unlocked_multiplier=True, lithography_nm=14),

        dict(name="Intel Core i9-10900", brand="Intel", socket_id=lga1200.id,
             architecture="Comet Lake", series="Core Gen 10",
             cores=10, threads=20, base_clock_ghz=2.8, boost_clock_ghz=5.2,
             tdp_watts=65, memory_type="DDR4", max_memory_speed_mhz=2933,
             memory_channels=2, pcie_gen=3,
             integrated_graphics=True, igpu_model="Intel UHD Graphics 630", igpu_cores=24,
             cooler_included="Intel Stock Cooler", has_unlocked_multiplier=False, lithography_nm=14),

        dict(name="Intel Core i9-10900F", brand="Intel", socket_id=lga1200.id,
             architecture="Comet Lake", series="Core Gen 10",
             cores=10, threads=20, base_clock_ghz=2.8, boost_clock_ghz=5.2,
             tdp_watts=65, memory_type="DDR4", max_memory_speed_mhz=2933,
             memory_channels=2, pcie_gen=3,
             integrated_graphics=False,
             cooler_included="Intel Stock Cooler", has_unlocked_multiplier=False, lithography_nm=14),

        dict(name="Intel Core i7-10700K", brand="Intel", socket_id=lga1200.id,
             architecture="Comet Lake", series="Core Gen 10",
             cores=8, threads=16, base_clock_ghz=3.8, boost_clock_ghz=5.1,
             tdp_watts=125, memory_type="DDR4", max_memory_speed_mhz=2933,
             memory_channels=2, pcie_gen=3,
             integrated_graphics=True, igpu_model="Intel UHD Graphics 630", igpu_cores=24,
             cooler_included="Not Included", has_unlocked_multiplier=True, lithography_nm=14,
             msrp_usd=374),

        dict(name="Intel Core i7-10700KF", brand="Intel", socket_id=lga1200.id,
             architecture="Comet Lake", series="Core Gen 10",
             cores=8, threads=16, base_clock_ghz=3.8, boost_clock_ghz=5.1,
             tdp_watts=125, memory_type="DDR4", max_memory_speed_mhz=2933,
             memory_channels=2, pcie_gen=3,
             integrated_graphics=False,
             cooler_included="Not Included", has_unlocked_multiplier=True, lithography_nm=14),

        dict(name="Intel Core i7-10700", brand="Intel", socket_id=lga1200.id,
             architecture="Comet Lake", series="Core Gen 10",
             cores=8, threads=16, base_clock_ghz=2.9, boost_clock_ghz=4.8,
             tdp_watts=65, memory_type="DDR4", max_memory_speed_mhz=2933,
             memory_channels=2, pcie_gen=3,
             integrated_graphics=True, igpu_model="Intel UHD Graphics 630", igpu_cores=24,
             cooler_included="Intel Stock Cooler", has_unlocked_multiplier=False, lithography_nm=14),

        dict(name="Intel Core i7-10700F", brand="Intel", socket_id=lga1200.id,
             architecture="Comet Lake", series="Core Gen 10",
             cores=8, threads=16, base_clock_ghz=2.9, boost_clock_ghz=4.8,
             tdp_watts=65, memory_type="DDR4", max_memory_speed_mhz=2933,
             memory_channels=2, pcie_gen=3,
             integrated_graphics=False,
             cooler_included="Intel Stock Cooler", has_unlocked_multiplier=False, lithography_nm=14),

        dict(name="Intel Core i5-10600K", brand="Intel", socket_id=lga1200.id,
             architecture="Comet Lake", series="Core Gen 10",
             cores=6, threads=12, base_clock_ghz=4.1, boost_clock_ghz=4.8,
             tdp_watts=125, memory_type="DDR4", max_memory_speed_mhz=2666,
             memory_channels=2, pcie_gen=3,
             integrated_graphics=True, igpu_model="Intel UHD Graphics 630", igpu_cores=24,
             cooler_included="Not Included", has_unlocked_multiplier=True, lithography_nm=14,
             msrp_usd=262),

        dict(name="Intel Core i5-10600KF", brand="Intel", socket_id=lga1200.id,
             architecture="Comet Lake", series="Core Gen 10",
             cores=6, threads=12, base_clock_ghz=4.1, boost_clock_ghz=4.8,
             tdp_watts=125, memory_type="DDR4", max_memory_speed_mhz=2666,
             memory_channels=2, pcie_gen=3,
             integrated_graphics=False,
             cooler_included="Not Included", has_unlocked_multiplier=True, lithography_nm=14),

        dict(name="Intel Core i5-10600", brand="Intel", socket_id=lga1200.id,
             architecture="Comet Lake", series="Core Gen 10",
             cores=6, threads=12, base_clock_ghz=3.3, boost_clock_ghz=4.8,
             tdp_watts=65, memory_type="DDR4", max_memory_speed_mhz=2666,
             memory_channels=2, pcie_gen=3,
             integrated_graphics=True, igpu_model="Intel UHD Graphics 630", igpu_cores=24,
             cooler_included="Intel Stock Cooler", has_unlocked_multiplier=False, lithography_nm=14),

        dict(name="Intel Core i5-10500", brand="Intel", socket_id=lga1200.id,
             architecture="Comet Lake", series="Core Gen 10",
             cores=6, threads=12, base_clock_ghz=3.1, boost_clock_ghz=4.5,
             tdp_watts=65, memory_type="DDR4", max_memory_speed_mhz=2666,
             memory_channels=2, pcie_gen=3,
             integrated_graphics=True, igpu_model="Intel UHD Graphics 630", igpu_cores=24,
             cooler_included="Intel Stock Cooler", has_unlocked_multiplier=False, lithography_nm=14),

        dict(name="Intel Core i5-10400", brand="Intel", socket_id=lga1200.id,
             architecture="Comet Lake", series="Core Gen 10",
             cores=6, threads=12, base_clock_ghz=2.9, boost_clock_ghz=4.3,
             tdp_watts=65, memory_type="DDR4", max_memory_speed_mhz=2666,
             memory_channels=2, pcie_gen=3,
             integrated_graphics=True, igpu_model="Intel UHD Graphics 630", igpu_cores=24,
             cooler_included="Intel Stock Cooler", has_unlocked_multiplier=False, lithography_nm=14,
             msrp_usd=182),

        dict(name="Intel Core i5-10400F", brand="Intel", socket_id=lga1200.id,
             architecture="Comet Lake", series="Core Gen 10",
             cores=6, threads=12, base_clock_ghz=2.9, boost_clock_ghz=4.3,
             tdp_watts=65, memory_type="DDR4", max_memory_speed_mhz=2666,
             memory_channels=2, pcie_gen=3,
             integrated_graphics=False,
             cooler_included="Intel Stock Cooler", has_unlocked_multiplier=False, lithography_nm=14,
             msrp_usd=157),

        dict(name="Intel Core i3-10320", brand="Intel", socket_id=lga1200.id,
             architecture="Comet Lake", series="Core Gen 10",
             cores=4, threads=8, base_clock_ghz=3.8, boost_clock_ghz=4.6,
             tdp_watts=65, memory_type="DDR4", max_memory_speed_mhz=2666,
             memory_channels=2, pcie_gen=3,
             integrated_graphics=True, igpu_model="Intel UHD Graphics 630", igpu_cores=24,
             cooler_included="Intel Stock Cooler", has_unlocked_multiplier=False, lithography_nm=14),

        dict(name="Intel Core i3-10300", brand="Intel", socket_id=lga1200.id,
             architecture="Comet Lake", series="Core Gen 10",
             cores=4, threads=8, base_clock_ghz=3.7, boost_clock_ghz=4.4,
             tdp_watts=65, memory_type="DDR4", max_memory_speed_mhz=2666,
             memory_channels=2, pcie_gen=3,
             integrated_graphics=True, igpu_model="Intel UHD Graphics 630", igpu_cores=24,
             cooler_included="Intel Stock Cooler", has_unlocked_multiplier=False, lithography_nm=14),

        dict(name="Intel Core i3-10100", brand="Intel", socket_id=lga1200.id,
             architecture="Comet Lake", series="Core Gen 10",
             cores=4, threads=8, base_clock_ghz=3.6, boost_clock_ghz=4.3,
             tdp_watts=65, memory_type="DDR4", max_memory_speed_mhz=2666,
             memory_channels=2, pcie_gen=3,
             integrated_graphics=True, igpu_model="Intel UHD Graphics 630", igpu_cores=24,
             cooler_included="Intel Stock Cooler", has_unlocked_multiplier=False, lithography_nm=14,
             msrp_usd=122),

        dict(name="Intel Core i3-10100F", brand="Intel", socket_id=lga1200.id,
             architecture="Comet Lake", series="Core Gen 10",
             cores=4, threads=8, base_clock_ghz=3.6, boost_clock_ghz=4.3,
             tdp_watts=65, memory_type="DDR4", max_memory_speed_mhz=2666,
             memory_channels=2, pcie_gen=3,
             integrated_graphics=False,
             cooler_included="Intel Stock Cooler", has_unlocked_multiplier=False, lithography_nm=14,
             msrp_usd=97),
    ])

    # ── Gen 11 (Rocket Lake, LGA1200) ────────────────────────────────────
    _add([
        dict(name="Intel Core i9-11900K", brand="Intel", socket_id=lga1200.id,
             architecture="Rocket Lake", series="Core Gen 11",
             cores=8, threads=16, base_clock_ghz=3.5, boost_clock_ghz=5.2,
             tdp_watts=125, memory_type="DDR4", max_memory_speed_mhz=3200,
             memory_channels=2, pcie_gen=4,
             integrated_graphics=True, igpu_model="Intel UHD Graphics 750", igpu_cores=32,
             cooler_included="Not Included", has_unlocked_multiplier=True, lithography_nm=14,
             msrp_usd=539),

        dict(name="Intel Core i9-11900KF", brand="Intel", socket_id=lga1200.id,
             architecture="Rocket Lake", series="Core Gen 11",
             cores=8, threads=16, base_clock_ghz=3.5, boost_clock_ghz=5.2,
             tdp_watts=125, memory_type="DDR4", max_memory_speed_mhz=3200,
             memory_channels=2, pcie_gen=4,
             integrated_graphics=False,
             cooler_included="Not Included", has_unlocked_multiplier=True, lithography_nm=14),

        dict(name="Intel Core i9-11900", brand="Intel", socket_id=lga1200.id,
             architecture="Rocket Lake", series="Core Gen 11",
             cores=8, threads=16, base_clock_ghz=2.5, boost_clock_ghz=5.2,
             tdp_watts=65, memory_type="DDR4", max_memory_speed_mhz=3200,
             memory_channels=2, pcie_gen=4,
             integrated_graphics=True, igpu_model="Intel UHD Graphics 750", igpu_cores=32,
             cooler_included="Intel Stock Cooler", has_unlocked_multiplier=False, lithography_nm=14),

        dict(name="Intel Core i9-11900F", brand="Intel", socket_id=lga1200.id,
             architecture="Rocket Lake", series="Core Gen 11",
             cores=8, threads=16, base_clock_ghz=2.5, boost_clock_ghz=5.2,
             tdp_watts=65, memory_type="DDR4", max_memory_speed_mhz=3200,
             memory_channels=2, pcie_gen=4,
             integrated_graphics=False,
             cooler_included="Intel Stock Cooler", has_unlocked_multiplier=False, lithography_nm=14),

        dict(name="Intel Core i7-11700K", brand="Intel", socket_id=lga1200.id,
             architecture="Rocket Lake", series="Core Gen 11",
             cores=8, threads=16, base_clock_ghz=3.6, boost_clock_ghz=5.0,
             tdp_watts=125, memory_type="DDR4", max_memory_speed_mhz=3200,
             memory_channels=2, pcie_gen=4,
             integrated_graphics=True, igpu_model="Intel UHD Graphics 750", igpu_cores=32,
             cooler_included="Not Included", has_unlocked_multiplier=True, lithography_nm=14,
             msrp_usd=399),

        dict(name="Intel Core i7-11700KF", brand="Intel", socket_id=lga1200.id,
             architecture="Rocket Lake", series="Core Gen 11",
             cores=8, threads=16, base_clock_ghz=3.6, boost_clock_ghz=5.0,
             tdp_watts=125, memory_type="DDR4", max_memory_speed_mhz=3200,
             memory_channels=2, pcie_gen=4,
             integrated_graphics=False,
             cooler_included="Not Included", has_unlocked_multiplier=True, lithography_nm=14),

        dict(name="Intel Core i7-11700", brand="Intel", socket_id=lga1200.id,
             architecture="Rocket Lake", series="Core Gen 11",
             cores=8, threads=16, base_clock_ghz=2.5, boost_clock_ghz=4.9,
             tdp_watts=65, memory_type="DDR4", max_memory_speed_mhz=3200,
             memory_channels=2, pcie_gen=4,
             integrated_graphics=True, igpu_model="Intel UHD Graphics 750", igpu_cores=32,
             cooler_included="Intel Stock Cooler", has_unlocked_multiplier=False, lithography_nm=14),

        dict(name="Intel Core i7-11700F", brand="Intel", socket_id=lga1200.id,
             architecture="Rocket Lake", series="Core Gen 11",
             cores=8, threads=16, base_clock_ghz=2.5, boost_clock_ghz=4.9,
             tdp_watts=65, memory_type="DDR4", max_memory_speed_mhz=3200,
             memory_channels=2, pcie_gen=4,
             integrated_graphics=False,
             cooler_included="Intel Stock Cooler", has_unlocked_multiplier=False, lithography_nm=14),

        dict(name="Intel Core i5-11600K", brand="Intel", socket_id=lga1200.id,
             architecture="Rocket Lake", series="Core Gen 11",
             cores=6, threads=12, base_clock_ghz=3.9, boost_clock_ghz=4.9,
             tdp_watts=125, memory_type="DDR4", max_memory_speed_mhz=3200,
             memory_channels=2, pcie_gen=4,
             integrated_graphics=True, igpu_model="Intel UHD Graphics 750", igpu_cores=32,
             cooler_included="Not Included", has_unlocked_multiplier=True, lithography_nm=14,
             msrp_usd=262),

        dict(name="Intel Core i5-11600KF", brand="Intel", socket_id=lga1200.id,
             architecture="Rocket Lake", series="Core Gen 11",
             cores=6, threads=12, base_clock_ghz=3.9, boost_clock_ghz=4.9,
             tdp_watts=125, memory_type="DDR4", max_memory_speed_mhz=3200,
             memory_channels=2, pcie_gen=4,
             integrated_graphics=False,
             cooler_included="Not Included", has_unlocked_multiplier=True, lithography_nm=14),

        dict(name="Intel Core i5-11600", brand="Intel", socket_id=lga1200.id,
             architecture="Rocket Lake", series="Core Gen 11",
             cores=6, threads=12, base_clock_ghz=2.8, boost_clock_ghz=4.8,
             tdp_watts=65, memory_type="DDR4", max_memory_speed_mhz=3200,
             memory_channels=2, pcie_gen=4,
             integrated_graphics=True, igpu_model="Intel UHD Graphics 750", igpu_cores=32,
             cooler_included="Intel Stock Cooler", has_unlocked_multiplier=False, lithography_nm=14),

        dict(name="Intel Core i5-11500", brand="Intel", socket_id=lga1200.id,
             architecture="Rocket Lake", series="Core Gen 11",
             cores=6, threads=12, base_clock_ghz=2.7, boost_clock_ghz=4.6,
             tdp_watts=65, memory_type="DDR4", max_memory_speed_mhz=3200,
             memory_channels=2, pcie_gen=4,
             integrated_graphics=True, igpu_model="Intel UHD Graphics 750", igpu_cores=32,
             cooler_included="Intel Stock Cooler", has_unlocked_multiplier=False, lithography_nm=14),

        dict(name="Intel Core i5-11400", brand="Intel", socket_id=lga1200.id,
             architecture="Rocket Lake", series="Core Gen 11",
             cores=6, threads=12, base_clock_ghz=2.6, boost_clock_ghz=4.4,
             tdp_watts=65, memory_type="DDR4", max_memory_speed_mhz=3200,
             memory_channels=2, pcie_gen=4,
             integrated_graphics=True, igpu_model="Intel UHD Graphics 730", igpu_cores=24,
             cooler_included="Intel Stock Cooler", has_unlocked_multiplier=False, lithography_nm=14,
             msrp_usd=182),

        dict(name="Intel Core i5-11400F", brand="Intel", socket_id=lga1200.id,
             architecture="Rocket Lake", series="Core Gen 11",
             cores=6, threads=12, base_clock_ghz=2.6, boost_clock_ghz=4.4,
             tdp_watts=65, memory_type="DDR4", max_memory_speed_mhz=3200,
             memory_channels=2, pcie_gen=4,
             integrated_graphics=False,
             cooler_included="Intel Stock Cooler", has_unlocked_multiplier=False, lithography_nm=14,
             msrp_usd=157),

        dict(name="Intel Core i3-11100", brand="Intel", socket_id=lga1200.id,
             architecture="Rocket Lake", series="Core Gen 11",
             cores=4, threads=8, base_clock_ghz=3.6, boost_clock_ghz=4.4,
             tdp_watts=65, memory_type="DDR4", max_memory_speed_mhz=3200,
             memory_channels=2, pcie_gen=4,
             integrated_graphics=True, igpu_model="Intel UHD Graphics 730", igpu_cores=24,
             cooler_included="Intel Stock Cooler", has_unlocked_multiplier=False, lithography_nm=14),

        dict(name="Intel Core i3-10105", brand="Intel", socket_id=lga1200.id,
             architecture="Comet Lake", series="Core Gen 10",
             cores=4, threads=8, base_clock_ghz=3.7, boost_clock_ghz=4.4,
             tdp_watts=65, memory_type="DDR4", max_memory_speed_mhz=2666,
             memory_channels=2, pcie_gen=3,
             integrated_graphics=True, igpu_model="Intel UHD Graphics 630", igpu_cores=24,
             cooler_included="Intel Stock Cooler", has_unlocked_multiplier=False, lithography_nm=14),
    ])

    # ── Gen 12 (Alder Lake, LGA1700) ─────────────────────────────────────
    _add([
        dict(name="Intel Core i9-12900KS", brand="Intel", socket_id=lga1700.id,
             architecture="Alder Lake", series="Core Gen 12",
             cores=16, threads=24, base_clock_ghz=3.4, boost_clock_ghz=5.5,
             tdp_watts=150, memory_type="DDR4/DDR5", max_memory_speed_mhz=5200,
             memory_channels=2, pcie_gen=5,
             integrated_graphics=True, igpu_model="Intel UHD Graphics 770", igpu_cores=32,
             cooler_included="Not Included", has_unlocked_multiplier=True, lithography_nm=10,
             msrp_usd=739),

        dict(name="Intel Core i9-12900K", brand="Intel", socket_id=lga1700.id,
             architecture="Alder Lake", series="Core Gen 12",
             cores=16, threads=24, base_clock_ghz=3.2, boost_clock_ghz=5.2,
             tdp_watts=125, memory_type="DDR4/DDR5", max_memory_speed_mhz=5200,
             memory_channels=2, pcie_gen=5,
             integrated_graphics=True, igpu_model="Intel UHD Graphics 770", igpu_cores=32,
             cooler_included="Not Included", has_unlocked_multiplier=True, lithography_nm=10,
             msrp_usd=589),

        dict(name="Intel Core i9-12900KF", brand="Intel", socket_id=lga1700.id,
             architecture="Alder Lake", series="Core Gen 12",
             cores=16, threads=24, base_clock_ghz=3.2, boost_clock_ghz=5.2,
             tdp_watts=125, memory_type="DDR4/DDR5", max_memory_speed_mhz=5200,
             memory_channels=2, pcie_gen=5,
             integrated_graphics=False,
             cooler_included="Not Included", has_unlocked_multiplier=True, lithography_nm=10,
             msrp_usd=564),

        dict(name="Intel Core i9-12900", brand="Intel", socket_id=lga1700.id,
             architecture="Alder Lake", series="Core Gen 12",
             cores=16, threads=24, base_clock_ghz=2.4, boost_clock_ghz=5.1,
             tdp_watts=65, memory_type="DDR4/DDR5", max_memory_speed_mhz=5200,
             memory_channels=2, pcie_gen=5,
             integrated_graphics=True, igpu_model="Intel UHD Graphics 770", igpu_cores=32,
             cooler_included="Intel Laminar RH1", has_unlocked_multiplier=False, lithography_nm=10),

        dict(name="Intel Core i9-12900F", brand="Intel", socket_id=lga1700.id,
             architecture="Alder Lake", series="Core Gen 12",
             cores=16, threads=24, base_clock_ghz=2.4, boost_clock_ghz=5.1,
             tdp_watts=65, memory_type="DDR4/DDR5", max_memory_speed_mhz=5200,
             memory_channels=2, pcie_gen=5,
             integrated_graphics=False,
             cooler_included="Intel Laminar RH1", has_unlocked_multiplier=False, lithography_nm=10),

        dict(name="Intel Core i7-12700K", brand="Intel", socket_id=lga1700.id,
             architecture="Alder Lake", series="Core Gen 12",
             cores=12, threads=20, base_clock_ghz=3.6, boost_clock_ghz=5.0,
             tdp_watts=125, memory_type="DDR4/DDR5", max_memory_speed_mhz=5200,
             memory_channels=2, pcie_gen=5,
             integrated_graphics=True, igpu_model="Intel UHD Graphics 770", igpu_cores=32,
             cooler_included="Not Included", has_unlocked_multiplier=True, lithography_nm=10,
             msrp_usd=409),

        dict(name="Intel Core i7-12700KF", brand="Intel", socket_id=lga1700.id,
             architecture="Alder Lake", series="Core Gen 12",
             cores=12, threads=20, base_clock_ghz=3.6, boost_clock_ghz=5.0,
             tdp_watts=125, memory_type="DDR4/DDR5", max_memory_speed_mhz=5200,
             memory_channels=2, pcie_gen=5,
             integrated_graphics=False,
             cooler_included="Not Included", has_unlocked_multiplier=True, lithography_nm=10),

        dict(name="Intel Core i7-12700", brand="Intel", socket_id=lga1700.id,
             architecture="Alder Lake", series="Core Gen 12",
             cores=12, threads=20, base_clock_ghz=2.1, boost_clock_ghz=4.9,
             tdp_watts=65, memory_type="DDR4/DDR5", max_memory_speed_mhz=5200,
             memory_channels=2, pcie_gen=5,
             integrated_graphics=True, igpu_model="Intel UHD Graphics 770", igpu_cores=32,
             cooler_included="Intel Laminar RM1", has_unlocked_multiplier=False, lithography_nm=10),

        dict(name="Intel Core i7-12700F", brand="Intel", socket_id=lga1700.id,
             architecture="Alder Lake", series="Core Gen 12",
             cores=12, threads=20, base_clock_ghz=2.1, boost_clock_ghz=4.9,
             tdp_watts=65, memory_type="DDR4/DDR5", max_memory_speed_mhz=5200,
             memory_channels=2, pcie_gen=5,
             integrated_graphics=False,
             cooler_included="Intel Laminar RM1", has_unlocked_multiplier=False, lithography_nm=10),

        dict(name="Intel Core i5-12600K", brand="Intel", socket_id=lga1700.id,
             architecture="Alder Lake", series="Core Gen 12",
             cores=10, threads=16, base_clock_ghz=3.7, boost_clock_ghz=4.9,
             tdp_watts=125, memory_type="DDR4/DDR5", max_memory_speed_mhz=5200,
             memory_channels=2, pcie_gen=5,
             integrated_graphics=True, igpu_model="Intel UHD Graphics 770", igpu_cores=32,
             cooler_included="Not Included", has_unlocked_multiplier=True, lithography_nm=10,
             msrp_usd=289),

        dict(name="Intel Core i5-12600KF", brand="Intel", socket_id=lga1700.id,
             architecture="Alder Lake", series="Core Gen 12",
             cores=10, threads=16, base_clock_ghz=3.7, boost_clock_ghz=4.9,
             tdp_watts=125, memory_type="DDR4/DDR5", max_memory_speed_mhz=5200,
             memory_channels=2, pcie_gen=5,
             integrated_graphics=False,
             cooler_included="Not Included", has_unlocked_multiplier=True, lithography_nm=10),

        dict(name="Intel Core i5-12600", brand="Intel", socket_id=lga1700.id,
             architecture="Alder Lake", series="Core Gen 12",
             cores=6, threads=12, base_clock_ghz=3.3, boost_clock_ghz=4.8,
             tdp_watts=65, memory_type="DDR4/DDR5", max_memory_speed_mhz=5200,
             memory_channels=2, pcie_gen=5,
             integrated_graphics=True, igpu_model="Intel UHD Graphics 770", igpu_cores=32,
             cooler_included="Intel Laminar RM1", has_unlocked_multiplier=False, lithography_nm=10),

        dict(name="Intel Core i5-12500", brand="Intel", socket_id=lga1700.id,
             architecture="Alder Lake", series="Core Gen 12",
             cores=6, threads=12, base_clock_ghz=3.0, boost_clock_ghz=4.6,
             tdp_watts=65, memory_type="DDR4/DDR5", max_memory_speed_mhz=5200,
             memory_channels=2, pcie_gen=5,
             integrated_graphics=True, igpu_model="Intel UHD Graphics 770", igpu_cores=32,
             cooler_included="Intel Laminar RM1", has_unlocked_multiplier=False, lithography_nm=10),

        dict(name="Intel Core i5-12490F", brand="Intel", socket_id=lga1700.id,
             architecture="Alder Lake", series="Core Gen 12",
             cores=6, threads=12, base_clock_ghz=3.0, boost_clock_ghz=4.6,
             tdp_watts=65, memory_type="DDR4/DDR5", max_memory_speed_mhz=5200,
             memory_channels=2, pcie_gen=5,
             integrated_graphics=False,
             cooler_included="Intel Laminar RM1", has_unlocked_multiplier=False, lithography_nm=10),

        dict(name="Intel Core i5-12400", brand="Intel", socket_id=lga1700.id,
             architecture="Alder Lake", series="Core Gen 12",
             cores=6, threads=12, base_clock_ghz=2.5, boost_clock_ghz=4.4,
             tdp_watts=65, memory_type="DDR4/DDR5", max_memory_speed_mhz=5200,
             memory_channels=2, pcie_gen=5,
             integrated_graphics=True, igpu_model="Intel UHD Graphics 730", igpu_cores=24,
             cooler_included="Intel Laminar RM1", has_unlocked_multiplier=False, lithography_nm=10,
             msrp_usd=192),

        dict(name="Intel Core i5-12400F", brand="Intel", socket_id=lga1700.id,
             architecture="Alder Lake", series="Core Gen 12",
             cores=6, threads=12, base_clock_ghz=2.5, boost_clock_ghz=4.4,
             tdp_watts=65, memory_type="DDR4/DDR5", max_memory_speed_mhz=5200,
             memory_channels=2, pcie_gen=5,
             integrated_graphics=False,
             cooler_included="Intel Laminar RM1", has_unlocked_multiplier=False, lithography_nm=10,
             msrp_usd=167),

        dict(name="Intel Core i3-12300", brand="Intel", socket_id=lga1700.id,
             architecture="Alder Lake", series="Core Gen 12",
             cores=4, threads=8, base_clock_ghz=3.5, boost_clock_ghz=4.4,
             tdp_watts=60, memory_type="DDR4/DDR5", max_memory_speed_mhz=5200,
             memory_channels=2, pcie_gen=5,
             integrated_graphics=True, igpu_model="Intel UHD Graphics 730", igpu_cores=24,
             cooler_included="Intel Laminar RM1", has_unlocked_multiplier=False, lithography_nm=10),

        dict(name="Intel Core i3-12100", brand="Intel", socket_id=lga1700.id,
             architecture="Alder Lake", series="Core Gen 12",
             cores=4, threads=8, base_clock_ghz=3.3, boost_clock_ghz=4.3,
             tdp_watts=60, memory_type="DDR4/DDR5", max_memory_speed_mhz=5200,
             memory_channels=2, pcie_gen=5,
             integrated_graphics=True, igpu_model="Intel UHD Graphics 730", igpu_cores=24,
             cooler_included="Intel Laminar RM1", has_unlocked_multiplier=False, lithography_nm=10,
             msrp_usd=122),

        dict(name="Intel Core i3-12100F", brand="Intel", socket_id=lga1700.id,
             architecture="Alder Lake", series="Core Gen 12",
             cores=4, threads=8, base_clock_ghz=3.3, boost_clock_ghz=4.3,
             tdp_watts=58, memory_type="DDR4/DDR5", max_memory_speed_mhz=5200,
             memory_channels=2, pcie_gen=5,
             integrated_graphics=False,
             cooler_included="Intel Laminar RM1", has_unlocked_multiplier=False, lithography_nm=10,
             msrp_usd=97),
    ])

    # ── Gen 13 (Raptor Lake, LGA1700) ────────────────────────────────────
    _add([
        dict(name="Intel Core i9-13900KS", brand="Intel", socket_id=lga1700.id,
             architecture="Raptor Lake", series="Core Gen 13",
             cores=24, threads=32, base_clock_ghz=3.2, boost_clock_ghz=6.0,
             tdp_watts=150, memory_type="DDR4/DDR5", max_memory_speed_mhz=6000,
             memory_channels=2, pcie_gen=5,
             integrated_graphics=True, igpu_model="Intel UHD Graphics 770", igpu_cores=32,
             cooler_included="Not Included", has_unlocked_multiplier=True, lithography_nm=10,
             msrp_usd=699),

        dict(name="Intel Core i9-13900K", brand="Intel", socket_id=lga1700.id,
             architecture="Raptor Lake", series="Core Gen 13",
             cores=24, threads=32, base_clock_ghz=3.0, boost_clock_ghz=5.8,
             tdp_watts=125, memory_type="DDR4/DDR5", max_memory_speed_mhz=5600,
             memory_channels=2, pcie_gen=5,
             integrated_graphics=True, igpu_model="Intel UHD Graphics 770", igpu_cores=32,
             cooler_included="Not Included", has_unlocked_multiplier=True, lithography_nm=10,
             msrp_usd=589),

        dict(name="Intel Core i9-13900KF", brand="Intel", socket_id=lga1700.id,
             architecture="Raptor Lake", series="Core Gen 13",
             cores=24, threads=32, base_clock_ghz=3.0, boost_clock_ghz=5.8,
             tdp_watts=125, memory_type="DDR4/DDR5", max_memory_speed_mhz=5600,
             memory_channels=2, pcie_gen=5,
             integrated_graphics=False,
             cooler_included="Not Included", has_unlocked_multiplier=True, lithography_nm=10,
             msrp_usd=564),

        dict(name="Intel Core i9-13900", brand="Intel", socket_id=lga1700.id,
             architecture="Raptor Lake", series="Core Gen 13",
             cores=24, threads=32, base_clock_ghz=2.0, boost_clock_ghz=5.6,
             tdp_watts=65, memory_type="DDR4/DDR5", max_memory_speed_mhz=5600,
             memory_channels=2, pcie_gen=5,
             integrated_graphics=True, igpu_model="Intel UHD Graphics 770", igpu_cores=32,
             cooler_included="Intel Laminar RH1", has_unlocked_multiplier=False, lithography_nm=10),

        dict(name="Intel Core i9-13900F", brand="Intel", socket_id=lga1700.id,
             architecture="Raptor Lake", series="Core Gen 13",
             cores=24, threads=32, base_clock_ghz=2.0, boost_clock_ghz=5.6,
             tdp_watts=65, memory_type="DDR4/DDR5", max_memory_speed_mhz=5600,
             memory_channels=2, pcie_gen=5,
             integrated_graphics=False,
             cooler_included="Intel Laminar RH1", has_unlocked_multiplier=False, lithography_nm=10),

        dict(name="Intel Core i7-13700K", brand="Intel", socket_id=lga1700.id,
             architecture="Raptor Lake", series="Core Gen 13",
             cores=16, threads=24, base_clock_ghz=3.4, boost_clock_ghz=5.4,
             tdp_watts=125, memory_type="DDR4/DDR5", max_memory_speed_mhz=5600,
             memory_channels=2, pcie_gen=5,
             integrated_graphics=True, igpu_model="Intel UHD Graphics 770", igpu_cores=32,
             cooler_included="Not Included", has_unlocked_multiplier=True, lithography_nm=10,
             msrp_usd=409),

        dict(name="Intel Core i7-13700KF", brand="Intel", socket_id=lga1700.id,
             architecture="Raptor Lake", series="Core Gen 13",
             cores=16, threads=24, base_clock_ghz=3.4, boost_clock_ghz=5.4,
             tdp_watts=125, memory_type="DDR4/DDR5", max_memory_speed_mhz=5600,
             memory_channels=2, pcie_gen=5,
             integrated_graphics=False,
             cooler_included="Not Included", has_unlocked_multiplier=True, lithography_nm=10),

        dict(name="Intel Core i7-13700", brand="Intel", socket_id=lga1700.id,
             architecture="Raptor Lake", series="Core Gen 13",
             cores=16, threads=24, base_clock_ghz=2.1, boost_clock_ghz=5.2,
             tdp_watts=65, memory_type="DDR4/DDR5", max_memory_speed_mhz=5600,
             memory_channels=2, pcie_gen=5,
             integrated_graphics=True, igpu_model="Intel UHD Graphics 770", igpu_cores=32,
             cooler_included="Intel Laminar RM1", has_unlocked_multiplier=False, lithography_nm=10),

        dict(name="Intel Core i7-13700F", brand="Intel", socket_id=lga1700.id,
             architecture="Raptor Lake", series="Core Gen 13",
             cores=16, threads=24, base_clock_ghz=2.1, boost_clock_ghz=5.2,
             tdp_watts=65, memory_type="DDR4/DDR5", max_memory_speed_mhz=5600,
             memory_channels=2, pcie_gen=5,
             integrated_graphics=False,
             cooler_included="Intel Laminar RM1", has_unlocked_multiplier=False, lithography_nm=10),

        dict(name="Intel Core i5-13600K", brand="Intel", socket_id=lga1700.id,
             architecture="Raptor Lake", series="Core Gen 13",
             cores=14, threads=20, base_clock_ghz=3.5, boost_clock_ghz=5.1,
             tdp_watts=125, memory_type="DDR4/DDR5", max_memory_speed_mhz=5600,
             memory_channels=2, pcie_gen=5,
             integrated_graphics=True, igpu_model="Intel UHD Graphics 770", igpu_cores=32,
             cooler_included="Not Included", has_unlocked_multiplier=True, lithography_nm=10,
             msrp_usd=319),

        dict(name="Intel Core i5-13600KF", brand="Intel", socket_id=lga1700.id,
             architecture="Raptor Lake", series="Core Gen 13",
             cores=14, threads=20, base_clock_ghz=3.5, boost_clock_ghz=5.1,
             tdp_watts=125, memory_type="DDR4/DDR5", max_memory_speed_mhz=5600,
             memory_channels=2, pcie_gen=5,
             integrated_graphics=False,
             cooler_included="Not Included", has_unlocked_multiplier=True, lithography_nm=10,
             msrp_usd=294),

        dict(name="Intel Core i5-13600", brand="Intel", socket_id=lga1700.id,
             architecture="Raptor Lake", series="Core Gen 13",
             cores=14, threads=20, base_clock_ghz=2.7, boost_clock_ghz=5.0,
             tdp_watts=65, memory_type="DDR4/DDR5", max_memory_speed_mhz=5600,
             memory_channels=2, pcie_gen=5,
             integrated_graphics=True, igpu_model="Intel UHD Graphics 770", igpu_cores=32,
             cooler_included="Intel Laminar RM1", has_unlocked_multiplier=False, lithography_nm=10),

        dict(name="Intel Core i5-13500", brand="Intel", socket_id=lga1700.id,
             architecture="Raptor Lake", series="Core Gen 13",
             cores=14, threads=20, base_clock_ghz=2.5, boost_clock_ghz=4.8,
             tdp_watts=65, memory_type="DDR4/DDR5", max_memory_speed_mhz=5600,
             memory_channels=2, pcie_gen=5,
             integrated_graphics=True, igpu_model="Intel UHD Graphics 770", igpu_cores=32,
             cooler_included="Intel Laminar RM1", has_unlocked_multiplier=False, lithography_nm=10),

        dict(name="Intel Core i5-13490F", brand="Intel", socket_id=lga1700.id,
             architecture="Raptor Lake", series="Core Gen 13",
             cores=10, threads=16, base_clock_ghz=2.5, boost_clock_ghz=4.8,
             tdp_watts=65, memory_type="DDR4/DDR5", max_memory_speed_mhz=5600,
             memory_channels=2, pcie_gen=5,
             integrated_graphics=False,
             cooler_included="Intel Laminar RM1", has_unlocked_multiplier=False, lithography_nm=10),

        dict(name="Intel Core i5-13400", brand="Intel", socket_id=lga1700.id,
             architecture="Raptor Lake", series="Core Gen 13",
             cores=10, threads=16, base_clock_ghz=2.5, boost_clock_ghz=4.6,
             tdp_watts=65, memory_type="DDR4/DDR5", max_memory_speed_mhz=5600,
             memory_channels=2, pcie_gen=5,
             integrated_graphics=True, igpu_model="Intel UHD Graphics 730", igpu_cores=24,
             cooler_included="Intel Laminar RM1", has_unlocked_multiplier=False, lithography_nm=10,
             msrp_usd=221),

        dict(name="Intel Core i5-13400F", brand="Intel", socket_id=lga1700.id,
             architecture="Raptor Lake", series="Core Gen 13",
             cores=10, threads=16, base_clock_ghz=2.5, boost_clock_ghz=4.6,
             tdp_watts=65, memory_type="DDR4/DDR5", max_memory_speed_mhz=5600,
             memory_channels=2, pcie_gen=5,
             integrated_graphics=False,
             cooler_included="Intel Laminar RM1", has_unlocked_multiplier=False, lithography_nm=10,
             msrp_usd=196),

        dict(name="Intel Core i3-13100", brand="Intel", socket_id=lga1700.id,
             architecture="Raptor Lake", series="Core Gen 13",
             cores=4, threads=8, base_clock_ghz=3.4, boost_clock_ghz=4.5,
             tdp_watts=60, memory_type="DDR4/DDR5", max_memory_speed_mhz=5600,
             memory_channels=2, pcie_gen=5,
             integrated_graphics=True, igpu_model="Intel UHD Graphics 730", igpu_cores=24,
             cooler_included="Intel Laminar RM1", has_unlocked_multiplier=False, lithography_nm=10,
             msrp_usd=134),

        dict(name="Intel Core i3-13100F", brand="Intel", socket_id=lga1700.id,
             architecture="Raptor Lake", series="Core Gen 13",
             cores=4, threads=8, base_clock_ghz=3.4, boost_clock_ghz=4.5,
             tdp_watts=58, memory_type="DDR4/DDR5", max_memory_speed_mhz=5600,
             memory_channels=2, pcie_gen=5,
             integrated_graphics=False,
             cooler_included="Intel Laminar RM1", has_unlocked_multiplier=False, lithography_nm=10,
             msrp_usd=109),
    ])

    # ── Gen 14 (Raptor Lake Refresh, LGA1700) ────────────────────────────
    _add([
        dict(name="Intel Core i9-14900KS", brand="Intel", socket_id=lga1700.id,
             architecture="Raptor Lake Refresh", series="Core Gen 14",
             cores=24, threads=32, base_clock_ghz=3.2, boost_clock_ghz=6.2,
             tdp_watts=150, memory_type="DDR4/DDR5", max_memory_speed_mhz=6000,
             memory_channels=2, pcie_gen=5,
             integrated_graphics=True, igpu_model="Intel UHD Graphics 770", igpu_cores=32,
             cooler_included="Not Included", has_unlocked_multiplier=True, lithography_nm=10,
             msrp_usd=699),

        dict(name="Intel Core i9-14900K", brand="Intel", socket_id=lga1700.id,
             architecture="Raptor Lake Refresh", series="Core Gen 14",
             cores=24, threads=32, base_clock_ghz=3.2, boost_clock_ghz=6.0,
             tdp_watts=125, memory_type="DDR4/DDR5", max_memory_speed_mhz=5600,
             memory_channels=2, pcie_gen=5,
             integrated_graphics=True, igpu_model="Intel UHD Graphics 770", igpu_cores=32,
             cooler_included="Not Included", has_unlocked_multiplier=True, lithography_nm=10,
             msrp_usd=589),

        dict(name="Intel Core i9-14900KF", brand="Intel", socket_id=lga1700.id,
             architecture="Raptor Lake Refresh", series="Core Gen 14",
             cores=24, threads=32, base_clock_ghz=3.2, boost_clock_ghz=6.0,
             tdp_watts=125, memory_type="DDR4/DDR5", max_memory_speed_mhz=5600,
             memory_channels=2, pcie_gen=5,
             integrated_graphics=False,
             cooler_included="Not Included", has_unlocked_multiplier=True, lithography_nm=10,
             msrp_usd=564),

        dict(name="Intel Core i9-14900", brand="Intel", socket_id=lga1700.id,
             architecture="Raptor Lake Refresh", series="Core Gen 14",
             cores=24, threads=32, base_clock_ghz=2.0, boost_clock_ghz=5.8,
             tdp_watts=65, memory_type="DDR4/DDR5", max_memory_speed_mhz=5600,
             memory_channels=2, pcie_gen=5,
             integrated_graphics=True, igpu_model="Intel UHD Graphics 770", igpu_cores=32,
             cooler_included="Intel Laminar RH1", has_unlocked_multiplier=False, lithography_nm=10),

        dict(name="Intel Core i9-14900F", brand="Intel", socket_id=lga1700.id,
             architecture="Raptor Lake Refresh", series="Core Gen 14",
             cores=24, threads=32, base_clock_ghz=2.0, boost_clock_ghz=5.8,
             tdp_watts=65, memory_type="DDR4/DDR5", max_memory_speed_mhz=5600,
             memory_channels=2, pcie_gen=5,
             integrated_graphics=False,
             cooler_included="Intel Laminar RH1", has_unlocked_multiplier=False, lithography_nm=10),

        dict(name="Intel Core i7-14700K", brand="Intel", socket_id=lga1700.id,
             architecture="Raptor Lake Refresh", series="Core Gen 14",
             cores=20, threads=28, base_clock_ghz=3.4, boost_clock_ghz=5.6,
             tdp_watts=125, memory_type="DDR4/DDR5", max_memory_speed_mhz=5600,
             memory_channels=2, pcie_gen=5,
             integrated_graphics=True, igpu_model="Intel UHD Graphics 770", igpu_cores=32,
             cooler_included="Not Included", has_unlocked_multiplier=True, lithography_nm=10,
             msrp_usd=409),

        dict(name="Intel Core i7-14700KF", brand="Intel", socket_id=lga1700.id,
             architecture="Raptor Lake Refresh", series="Core Gen 14",
             cores=20, threads=28, base_clock_ghz=3.4, boost_clock_ghz=5.6,
             tdp_watts=125, memory_type="DDR4/DDR5", max_memory_speed_mhz=5600,
             memory_channels=2, pcie_gen=5,
             integrated_graphics=False,
             cooler_included="Not Included", has_unlocked_multiplier=True, lithography_nm=10),

        dict(name="Intel Core i7-14700", brand="Intel", socket_id=lga1700.id,
             architecture="Raptor Lake Refresh", series="Core Gen 14",
             cores=20, threads=28, base_clock_ghz=2.1, boost_clock_ghz=5.4,
             tdp_watts=65, memory_type="DDR4/DDR5", max_memory_speed_mhz=5600,
             memory_channels=2, pcie_gen=5,
             integrated_graphics=True, igpu_model="Intel UHD Graphics 770", igpu_cores=32,
             cooler_included="Intel Laminar RM1", has_unlocked_multiplier=False, lithography_nm=10),

        dict(name="Intel Core i7-14700F", brand="Intel", socket_id=lga1700.id,
             architecture="Raptor Lake Refresh", series="Core Gen 14",
             cores=20, threads=28, base_clock_ghz=2.1, boost_clock_ghz=5.4,
             tdp_watts=65, memory_type="DDR4/DDR5", max_memory_speed_mhz=5600,
             memory_channels=2, pcie_gen=5,
             integrated_graphics=False,
             cooler_included="Intel Laminar RM1", has_unlocked_multiplier=False, lithography_nm=10),

        dict(name="Intel Core i5-14600K", brand="Intel", socket_id=lga1700.id,
             architecture="Raptor Lake Refresh", series="Core Gen 14",
             cores=14, threads=20, base_clock_ghz=3.5, boost_clock_ghz=5.3,
             tdp_watts=125, memory_type="DDR4/DDR5", max_memory_speed_mhz=5600,
             memory_channels=2, pcie_gen=5,
             integrated_graphics=True, igpu_model="Intel UHD Graphics 770", igpu_cores=32,
             cooler_included="Not Included", has_unlocked_multiplier=True, lithography_nm=10,
             msrp_usd=319),

        dict(name="Intel Core i5-14600KF", brand="Intel", socket_id=lga1700.id,
             architecture="Raptor Lake Refresh", series="Core Gen 14",
             cores=14, threads=20, base_clock_ghz=3.5, boost_clock_ghz=5.3,
             tdp_watts=125, memory_type="DDR4/DDR5", max_memory_speed_mhz=5600,
             memory_channels=2, pcie_gen=5,
             integrated_graphics=False,
             cooler_included="Not Included", has_unlocked_multiplier=True, lithography_nm=10,
             msrp_usd=294),

        dict(name="Intel Core i5-14600", brand="Intel", socket_id=lga1700.id,
             architecture="Raptor Lake Refresh", series="Core Gen 14",
             cores=14, threads=20, base_clock_ghz=2.7, boost_clock_ghz=5.2,
             tdp_watts=65, memory_type="DDR4/DDR5", max_memory_speed_mhz=5600,
             memory_channels=2, pcie_gen=5,
             integrated_graphics=True, igpu_model="Intel UHD Graphics 770", igpu_cores=32,
             cooler_included="Intel Laminar RM1", has_unlocked_multiplier=False, lithography_nm=10),

        dict(name="Intel Core i5-14600T", brand="Intel", socket_id=lga1700.id,
             architecture="Raptor Lake Refresh", series="Core Gen 14",
             cores=14, threads=20, base_clock_ghz=1.8, boost_clock_ghz=5.0,
             tdp_watts=35, memory_type="DDR4/DDR5", max_memory_speed_mhz=5600,
             memory_channels=2, pcie_gen=5,
             integrated_graphics=True, igpu_model="Intel UHD Graphics 770", igpu_cores=32,
             cooler_included=None, has_unlocked_multiplier=False, lithography_nm=10),

        dict(name="Intel Core i5-14500", brand="Intel", socket_id=lga1700.id,
             architecture="Raptor Lake Refresh", series="Core Gen 14",
             cores=14, threads=20, base_clock_ghz=2.6, boost_clock_ghz=5.0,
             tdp_watts=65, memory_type="DDR4/DDR5", max_memory_speed_mhz=5600,
             memory_channels=2, pcie_gen=5,
             integrated_graphics=True, igpu_model="Intel UHD Graphics 770", igpu_cores=32,
             cooler_included="Intel Laminar RM1", has_unlocked_multiplier=False, lithography_nm=10),

        dict(name="Intel Core i5-14400", brand="Intel", socket_id=lga1700.id,
             architecture="Raptor Lake Refresh", series="Core Gen 14",
             cores=10, threads=16, base_clock_ghz=2.5, boost_clock_ghz=4.7,
             tdp_watts=65, memory_type="DDR4/DDR5", max_memory_speed_mhz=5600,
             memory_channels=2, pcie_gen=5,
             integrated_graphics=True, igpu_model="Intel UHD Graphics 730", igpu_cores=24,
             cooler_included="Intel Laminar RM1", has_unlocked_multiplier=False, lithography_nm=10,
             msrp_usd=221),

        dict(name="Intel Core i5-14400F", brand="Intel", socket_id=lga1700.id,
             architecture="Raptor Lake Refresh", series="Core Gen 14",
             cores=10, threads=16, base_clock_ghz=2.5, boost_clock_ghz=4.7,
             tdp_watts=65, memory_type="DDR4/DDR5", max_memory_speed_mhz=5600,
             memory_channels=2, pcie_gen=5,
             integrated_graphics=False,
             cooler_included="Intel Laminar RM1", has_unlocked_multiplier=False, lithography_nm=10,
             msrp_usd=196),

        dict(name="Intel Core i3-14100", brand="Intel", socket_id=lga1700.id,
             architecture="Raptor Lake Refresh", series="Core Gen 14",
             cores=4, threads=8, base_clock_ghz=3.5, boost_clock_ghz=4.7,
             tdp_watts=60, memory_type="DDR4/DDR5", max_memory_speed_mhz=5600,
             memory_channels=2, pcie_gen=5,
             integrated_graphics=True, igpu_model="Intel UHD Graphics 730", igpu_cores=24,
             cooler_included="Intel Laminar RM1", has_unlocked_multiplier=False, lithography_nm=10,
             msrp_usd=134),

        dict(name="Intel Core i3-14100F", brand="Intel", socket_id=lga1700.id,
             architecture="Raptor Lake Refresh", series="Core Gen 14",
             cores=4, threads=8, base_clock_ghz=3.5, boost_clock_ghz=4.7,
             tdp_watts=58, memory_type="DDR4/DDR5", max_memory_speed_mhz=5600,
             memory_channels=2, pcie_gen=5,
             integrated_graphics=False,
             cooler_included="Intel Laminar RM1", has_unlocked_multiplier=False, lithography_nm=10,
             msrp_usd=109),
    ])

    # ── Core Ultra 200 (Arrow Lake, LGA1851) ─────────────────────────────
    _add([
        dict(name="Intel Core Ultra 9 285K", brand="Intel", socket_id=lga1851.id,
             architecture="Arrow Lake", series="Core Ultra 200",
             cores=24, threads=24, base_clock_ghz=3.7, boost_clock_ghz=5.7,
             tdp_watts=125, memory_type="DDR5", max_memory_speed_mhz=9200,
             memory_channels=2, pcie_gen=5,
             integrated_graphics=True, igpu_model="Intel Arc Graphics 140V", igpu_cores=4,
             cooler_included="Not Included", has_unlocked_multiplier=True, lithography_nm=3,
             msrp_usd=589),

        dict(name="Intel Core Ultra 7 265K", brand="Intel", socket_id=lga1851.id,
             architecture="Arrow Lake", series="Core Ultra 200",
             cores=20, threads=20, base_clock_ghz=3.9, boost_clock_ghz=5.5,
             tdp_watts=125, memory_type="DDR5", max_memory_speed_mhz=9200,
             memory_channels=2, pcie_gen=5,
             integrated_graphics=True, igpu_model="Intel Arc Graphics 140V", igpu_cores=4,
             cooler_included="Not Included", has_unlocked_multiplier=True, lithography_nm=3,
             msrp_usd=394),

        dict(name="Intel Core Ultra 7 265KF", brand="Intel", socket_id=lga1851.id,
             architecture="Arrow Lake", series="Core Ultra 200",
             cores=20, threads=20, base_clock_ghz=3.9, boost_clock_ghz=5.5,
             tdp_watts=125, memory_type="DDR5", max_memory_speed_mhz=9200,
             memory_channels=2, pcie_gen=5,
             integrated_graphics=False,
             cooler_included="Not Included", has_unlocked_multiplier=True, lithography_nm=3,
             msrp_usd=369),

        dict(name="Intel Core Ultra 5 245K", brand="Intel", socket_id=lga1851.id,
             architecture="Arrow Lake", series="Core Ultra 200",
             cores=14, threads=14, base_clock_ghz=4.2, boost_clock_ghz=5.2,
             tdp_watts=125, memory_type="DDR5", max_memory_speed_mhz=9200,
             memory_channels=2, pcie_gen=5,
             integrated_graphics=True, igpu_model="Intel Arc Graphics 140V", igpu_cores=4,
             cooler_included="Not Included", has_unlocked_multiplier=True, lithography_nm=3,
             msrp_usd=309),

        dict(name="Intel Core Ultra 5 245KF", brand="Intel", socket_id=lga1851.id,
             architecture="Arrow Lake", series="Core Ultra 200",
             cores=14, threads=14, base_clock_ghz=4.2, boost_clock_ghz=5.2,
             tdp_watts=125, memory_type="DDR5", max_memory_speed_mhz=9200,
             memory_channels=2, pcie_gen=5,
             integrated_graphics=False,
             cooler_included="Not Included", has_unlocked_multiplier=True, lithography_nm=3,
             msrp_usd=284),
    ])

    db.session.commit()
