"""Seed 04 — NVIDIA GPUs."""

from models import db, GPU


def _add(gpus):
    for g in gpus:
        g.setdefault("compute_units", 0)
        if not GPU.query.filter_by(name=g["name"]).first():
            db.session.add(GPU(**g))
    db.session.flush()


def seed():
    _add([
        dict(name="NVIDIA GeForce GT 1030",
             brand="NVIDIA", architecture="Pascal", series="GeForce 10 Series (Pascal)",
             vram_gb=2, vram_type="GDDR5", bus_width_bits=64,
             base_clock_mhz=1227, boost_clock_mhz=1468,
             shaders=384, tdp_watts=30, min_psu_watts=300,
             power_connectors=None, card_length_mm=145, card_slots=1.0,
             pcie_interface="PCIe 3.0 x16", ray_tracing=False, dlss_version=None,
             display_outputs="HDMI,DP,DL-DVI", msrp_usd=79),

        dict(name="NVIDIA GeForce GTX 1050",
             brand="NVIDIA", architecture="Pascal", series="GeForce 10 Series (Pascal)",
             vram_gb=2, vram_type="GDDR5", bus_width_bits=128,
             base_clock_mhz=1354, boost_clock_mhz=1455,
             shaders=640, tdp_watts=75, min_psu_watts=300,
             power_connectors=None, card_length_mm=145, card_slots=2.0,
             pcie_interface="PCIe 3.0 x16", ray_tracing=False, dlss_version=None,
             display_outputs="HDMI,DP,DVI", msrp_usd=109),

        dict(name="NVIDIA GeForce GTX 1050 Ti",
             brand="NVIDIA", architecture="Pascal", series="GeForce 10 Series (Pascal)",
             vram_gb=4, vram_type="GDDR5", bus_width_bits=128,
             base_clock_mhz=1290, boost_clock_mhz=1392,
             shaders=768, tdp_watts=75, min_psu_watts=300,
             power_connectors=None, card_length_mm=145, card_slots=2.0,
             pcie_interface="PCIe 3.0 x16", ray_tracing=False, dlss_version=None,
             display_outputs="HDMI,DP,DVI", msrp_usd=139),

        dict(name="NVIDIA GeForce GTX 1060",
             brand="NVIDIA", architecture="Pascal", series="GeForce 10 Series (Pascal)",
             vram_gb=6, vram_type="GDDR5", bus_width_bits=192,
             base_clock_mhz=1506, boost_clock_mhz=1708,
             shaders=1280, tdp_watts=120, min_psu_watts=400,
             power_connectors="6pin", card_length_mm=240, card_slots=2.0,
             pcie_interface="PCIe 3.0 x16", ray_tracing=False, dlss_version=None,
             display_outputs="HDMI,DP,DVI", msrp_usd=249),

        dict(name="NVIDIA GeForce GTX 1070",
             brand="NVIDIA", architecture="Pascal", series="GeForce 10 Series (Pascal)",
             vram_gb=8, vram_type="GDDR5", bus_width_bits=256,
             base_clock_mhz=1506, boost_clock_mhz=1683,
             shaders=1920, tdp_watts=150, min_psu_watts=500,
             power_connectors="8pin", card_length_mm=241, card_slots=2.0,
             pcie_interface="PCIe 3.0 x16", ray_tracing=False, dlss_version=None,
             display_outputs="HDMI,DP,DVI", msrp_usd=379),

        dict(name="NVIDIA GeForce GTX 1070 Ti",
             brand="NVIDIA", architecture="Pascal", series="GeForce 10 Series (Pascal)",
             vram_gb=8, vram_type="GDDR5", bus_width_bits=256,
             base_clock_mhz=1607, boost_clock_mhz=1683,
             shaders=2432, tdp_watts=180, min_psu_watts=500,
             power_connectors="8pin", card_length_mm=241, card_slots=2.0,
             pcie_interface="PCIe 3.0 x16", ray_tracing=False, dlss_version=None,
             display_outputs="HDMI,DP,DVI", msrp_usd=429),

        dict(name="NVIDIA GeForce GTX 1080",
             brand="NVIDIA", architecture="Pascal", series="GeForce 10 Series (Pascal)",
             vram_gb=8, vram_type="GDDR5X", bus_width_bits=256,
             base_clock_mhz=1607, boost_clock_mhz=1733,
             shaders=2560, tdp_watts=180, min_psu_watts=500,
             power_connectors="8pin", card_length_mm=250, card_slots=2.0,
             pcie_interface="PCIe 3.0 x16", ray_tracing=False, dlss_version=None,
             display_outputs="HDMI,DP,DVI", msrp_usd=599),

        dict(name="NVIDIA GeForce GTX 1080 Ti",
             brand="NVIDIA", architecture="Pascal", series="GeForce 10 Series (Pascal)",
             vram_gb=11, vram_type="GDDR5X", bus_width_bits=352,
             base_clock_mhz=1480, boost_clock_mhz=1582,
             shaders=3584, tdp_watts=250, min_psu_watts=600,
             power_connectors="8pin,8pin", card_length_mm=267, card_slots=2.5,
             pcie_interface="PCIe 3.0 x16", ray_tracing=False, dlss_version=None,
             display_outputs="HDMI,DP,DP,DP", msrp_usd=699),

        dict(name="NVIDIA GeForce Titan X Pascal",
             brand="NVIDIA", architecture="Pascal", series="GeForce 10 Series (Pascal)",
             vram_gb=12, vram_type="GDDR5X", bus_width_bits=384,
             base_clock_mhz=1417, boost_clock_mhz=1531,
             shaders=3584, tdp_watts=250, min_psu_watts=600,
             power_connectors="8pin,8pin", card_length_mm=267, card_slots=2.5,
             pcie_interface="PCIe 3.0 x16", ray_tracing=False, dlss_version=None,
             display_outputs="HDMI,DP,DP,DP", msrp_usd=1199),

        dict(name="NVIDIA GeForce Titan Xp",
             brand="NVIDIA", architecture="Pascal", series="GeForce 10 Series (Pascal)",
             vram_gb=12, vram_type="GDDR5X", bus_width_bits=384,
             base_clock_mhz=1405, boost_clock_mhz=1582,
             shaders=3840, tdp_watts=250, min_psu_watts=600,
             power_connectors="8pin,8pin", card_length_mm=267, card_slots=2.5,
             pcie_interface="PCIe 3.0 x16", ray_tracing=False, dlss_version=None,
             display_outputs="HDMI,DP,DP,DP", msrp_usd=1199),

        dict(name="NVIDIA GeForce GTX 1630",
             brand="NVIDIA", architecture="Turing", series="GeForce 16 Series (Turing)",
             vram_gb=4, vram_type="GDDR6", bus_width_bits=64,
             base_clock_mhz=1740, boost_clock_mhz=1785,
             shaders=512, tdp_watts=75, min_psu_watts=300,
             power_connectors=None, card_length_mm=145, card_slots=2.0,
             pcie_interface="PCIe 4.0 x16", ray_tracing=False, dlss_version=None,
             display_outputs="HDMI,DP,DVI", msrp_usd=179),

        dict(name="NVIDIA GeForce GTX 1650",
             brand="NVIDIA", architecture="Turing", series="GeForce 16 Series (Turing)",
             vram_gb=4, vram_type="GDDR5", bus_width_bits=128,
             base_clock_mhz=1485, boost_clock_mhz=1665,
             shaders=896, tdp_watts=75, min_psu_watts=300,
             power_connectors=None, card_length_mm=170, card_slots=2.0,
             pcie_interface="PCIe 3.0 x16", ray_tracing=False, dlss_version=None,
             display_outputs="HDMI,DP,DVI", msrp_usd=149),

        dict(name="NVIDIA GeForce GTX 1650 SUPER",
             brand="NVIDIA", architecture="Turing", series="GeForce 16 Series (Turing)",
             vram_gb=4, vram_type="GDDR6", bus_width_bits=128,
             base_clock_mhz=1530, boost_clock_mhz=1725,
             shaders=1280, tdp_watts=100, min_psu_watts=350,
             power_connectors=None, card_length_mm=178, card_slots=2.0,
             pcie_interface="PCIe 3.0 x16", ray_tracing=False, dlss_version=None,
             display_outputs="HDMI,DP,DVI", msrp_usd=159),

        dict(name="NVIDIA GeForce GTX 1660",
             brand="NVIDIA", architecture="Turing", series="GeForce 16 Series (Turing)",
             vram_gb=6, vram_type="GDDR5", bus_width_bits=192,
             base_clock_mhz=1530, boost_clock_mhz=1785,
             shaders=1408, tdp_watts=120, min_psu_watts=450,
             power_connectors=None, card_length_mm=229, card_slots=2.0,
             pcie_interface="PCIe 3.0 x16", ray_tracing=False, dlss_version=None,
             display_outputs="HDMI,DP,DVI", msrp_usd=219),

        dict(name="NVIDIA GeForce GTX 1660 SUPER",
             brand="NVIDIA", architecture="Turing", series="GeForce 16 Series (Turing)",
             vram_gb=6, vram_type="GDDR6", bus_width_bits=192,
             base_clock_mhz=1530, boost_clock_mhz=1785,
             shaders=1408, tdp_watts=125, min_psu_watts=450,
             power_connectors=None, card_length_mm=229, card_slots=2.0,
             pcie_interface="PCIe 3.0 x16", ray_tracing=False, dlss_version=None,
             display_outputs="HDMI,DP,DVI", msrp_usd=229),

        dict(name="NVIDIA GeForce GTX 1660 Ti",
             brand="NVIDIA", architecture="Turing", series="GeForce 16 Series (Turing)",
             vram_gb=6, vram_type="GDDR6", bus_width_bits=192,
             base_clock_mhz=1500, boost_clock_mhz=1770,
             shaders=1536, tdp_watts=120, min_psu_watts=450,
             power_connectors=None, card_length_mm=229, card_slots=2.0,
             pcie_interface="PCIe 3.0 x16", ray_tracing=False, dlss_version=None,
             display_outputs="HDMI,DP,DVI", msrp_usd=279),

        dict(name="NVIDIA GeForce RTX 2060",
             brand="NVIDIA", architecture="Turing", series="RTX 20 Series (Turing)",
             vram_gb=6, vram_type="GDDR6", bus_width_bits=192,
             base_clock_mhz=1365, boost_clock_mhz=1680,
             shaders=1920, rt_cores=30, tensor_cores=240,
             tdp_watts=160, min_psu_watts=500,
             power_connectors="6pin", card_length_mm=229, card_slots=2.0,
             pcie_interface="PCIe 3.0 x16", ray_tracing=True, dlss_version="2.0",
             display_outputs="HDMI,DP,DP,DP", msrp_usd=349),

        dict(name="NVIDIA GeForce RTX 2060 SUPER",
             brand="NVIDIA", architecture="Turing", series="RTX 20 Series (Turing)",
             vram_gb=8, vram_type="GDDR6", bus_width_bits=256,
             base_clock_mhz=1470, boost_clock_mhz=1650,
             shaders=2176, rt_cores=34, tensor_cores=272,
             tdp_watts=175, min_psu_watts=550,
             power_connectors="8pin", card_length_mm=229, card_slots=2.0,
             pcie_interface="PCIe 3.0 x16", ray_tracing=True, dlss_version="2.0",
             display_outputs="HDMI,DP,DP,DP", msrp_usd=399),

        dict(name="NVIDIA GeForce RTX 2070",
             brand="NVIDIA", architecture="Turing", series="RTX 20 Series (Turing)",
             vram_gb=8, vram_type="GDDR6", bus_width_bits=256,
             base_clock_mhz=1410, boost_clock_mhz=1620,
             shaders=2304, rt_cores=36, tensor_cores=288,
             tdp_watts=175, min_psu_watts=550,
             power_connectors="8pin", card_length_mm=241, card_slots=2.0,
             pcie_interface="PCIe 3.0 x16", ray_tracing=True, dlss_version="2.0",
             display_outputs="HDMI,DP,DP,DP", msrp_usd=499),

        dict(name="NVIDIA GeForce RTX 2070 SUPER",
             brand="NVIDIA", architecture="Turing", series="RTX 20 Series (Turing)",
             vram_gb=8, vram_type="GDDR6", bus_width_bits=256,
             base_clock_mhz=1605, boost_clock_mhz=1770,
             shaders=2560, rt_cores=40, tensor_cores=320,
             tdp_watts=215, min_psu_watts=650,
             power_connectors="8pin", card_length_mm=241, card_slots=2.0,
             pcie_interface="PCIe 3.0 x16", ray_tracing=True, dlss_version="2.0",
             display_outputs="HDMI,DP,DP,DP", msrp_usd=499),

        dict(name="NVIDIA GeForce RTX 2080",
             brand="NVIDIA", architecture="Turing", series="RTX 20 Series (Turing)",
             vram_gb=8, vram_type="GDDR6", bus_width_bits=256,
             base_clock_mhz=1515, boost_clock_mhz=1710,
             shaders=2944, rt_cores=46, tensor_cores=368,
             tdp_watts=215, min_psu_watts=650,
             power_connectors="8pin,8pin", card_length_mm=267, card_slots=2.0,
             pcie_interface="PCIe 3.0 x16", ray_tracing=True, dlss_version="2.0",
             display_outputs="HDMI,DP,DP,DP", msrp_usd=699),

        dict(name="NVIDIA GeForce RTX 2080 SUPER",
             brand="NVIDIA", architecture="Turing", series="RTX 20 Series (Turing)",
             vram_gb=8, vram_type="GDDR6", bus_width_bits=256,
             base_clock_mhz=1650, boost_clock_mhz=1815,
             shaders=3072, rt_cores=48, tensor_cores=384,
             tdp_watts=250, min_psu_watts=650,
             power_connectors="8pin,8pin", card_length_mm=267, card_slots=2.0,
             pcie_interface="PCIe 3.0 x16", ray_tracing=True, dlss_version="2.0",
             display_outputs="HDMI,DP,DP,DP", msrp_usd=699),

        dict(name="NVIDIA GeForce RTX 2080 Ti",
             brand="NVIDIA", architecture="Turing", series="RTX 20 Series (Turing)",
             vram_gb=11, vram_type="GDDR6", bus_width_bits=352,
             base_clock_mhz=1350, boost_clock_mhz=1545,
             shaders=4352, rt_cores=68, tensor_cores=544,
             tdp_watts=250, min_psu_watts=650,
             power_connectors="8pin,8pin", card_length_mm=267, card_slots=2.0,
             pcie_interface="PCIe 3.0 x16", ray_tracing=True, dlss_version="2.0",
             display_outputs="HDMI,DP,DP,DP", msrp_usd=999),

        dict(name="NVIDIA GeForce Titan RTX",
             brand="NVIDIA", architecture="Turing", series="RTX 20 Series (Turing)",
             vram_gb=24, vram_type="GDDR6", bus_width_bits=384,
             base_clock_mhz=1350, boost_clock_mhz=1770,
             shaders=4608, rt_cores=72, tensor_cores=576,
             tdp_watts=280, min_psu_watts=650,
             power_connectors="8pin,8pin", card_length_mm=267, card_slots=2.5,
             pcie_interface="PCIe 3.0 x16", ray_tracing=True, dlss_version="2.0",
             display_outputs="HDMI,DP,DP,DP", msrp_usd=2499),

        dict(name="NVIDIA GeForce RTX 3050",
             brand="NVIDIA", architecture="Ampere", series="RTX 30 Series (Ampere)",
             vram_gb=8, vram_type="GDDR6", bus_width_bits=128,
             base_clock_mhz=1552, boost_clock_mhz=1777,
             shaders=2560, rt_cores=20, tensor_cores=80,
             tdp_watts=130, min_psu_watts=550,
             power_connectors=None, card_length_mm=182, card_slots=2.0,
             pcie_interface="PCIe 4.0 x16", ray_tracing=True, dlss_version="2.0",
             display_outputs="HDMI,DP,DP", msrp_usd=249),

        dict(name="NVIDIA GeForce RTX 3060",
             brand="NVIDIA", architecture="Ampere", series="RTX 30 Series (Ampere)",
             vram_gb=12, vram_type="GDDR6", bus_width_bits=192,
             base_clock_mhz=1320, boost_clock_mhz=1777,
             shaders=3584, rt_cores=28, tensor_cores=112,
             tdp_watts=170, min_psu_watts=550,
             power_connectors="8pin", card_length_mm=242, card_slots=2.0,
             pcie_interface="PCIe 4.0 x16", ray_tracing=True, dlss_version="2.0",
             display_outputs="HDMI,DP,DP,DP", msrp_usd=329),

        dict(name="NVIDIA GeForce RTX 3060 Ti",
             brand="NVIDIA", architecture="Ampere", series="RTX 30 Series (Ampere)",
             vram_gb=8, vram_type="GDDR6", bus_width_bits=256,
             base_clock_mhz=1410, boost_clock_mhz=1665,
             shaders=4864, rt_cores=38, tensor_cores=152,
             tdp_watts=200, min_psu_watts=600,
             power_connectors="8pin", card_length_mm=242, card_slots=2.0,
             pcie_interface="PCIe 4.0 x16", ray_tracing=True, dlss_version="2.0",
             display_outputs="HDMI,DP,DP,DP", msrp_usd=399),

        dict(name="NVIDIA GeForce RTX 3070",
             brand="NVIDIA", architecture="Ampere", series="RTX 30 Series (Ampere)",
             vram_gb=8, vram_type="GDDR6", bus_width_bits=256,
             base_clock_mhz=1500, boost_clock_mhz=1725,
             shaders=5888, rt_cores=46, tensor_cores=184,
             tdp_watts=220, min_psu_watts=650,
             power_connectors="8pin", card_length_mm=242, card_slots=2.0,
             pcie_interface="PCIe 4.0 x16", ray_tracing=True, dlss_version="2.0",
             display_outputs="HDMI,DP,DP,DP", msrp_usd=499),

        dict(name="NVIDIA GeForce RTX 3070 Ti",
             brand="NVIDIA", architecture="Ampere", series="RTX 30 Series (Ampere)",
             vram_gb=8, vram_type="GDDR6X", bus_width_bits=256,
             base_clock_mhz=1575, boost_clock_mhz=1770,
             shaders=6144, rt_cores=48, tensor_cores=192,
             tdp_watts=290, min_psu_watts=750,
             power_connectors="8pin", card_length_mm=242, card_slots=2.0,
             pcie_interface="PCIe 4.0 x16", ray_tracing=True, dlss_version="2.0",
             display_outputs="HDMI,DP,DP,DP", msrp_usd=599),

        dict(name="NVIDIA GeForce RTX 3080",
             brand="NVIDIA", architecture="Ampere", series="RTX 30 Series (Ampere)",
             vram_gb=10, vram_type="GDDR6X", bus_width_bits=320,
             base_clock_mhz=1440, boost_clock_mhz=1710,
             shaders=8704, rt_cores=68, tensor_cores=272,
             tdp_watts=320, min_psu_watts=750,
             power_connectors="8pin,8pin", card_length_mm=285, card_slots=2.0,
             pcie_interface="PCIe 4.0 x16", ray_tracing=True, dlss_version="2.0",
             display_outputs="HDMI,DP,DP,DP", msrp_usd=699),

        dict(name="NVIDIA GeForce RTX 3080 Ti",
             brand="NVIDIA", architecture="Ampere", series="RTX 30 Series (Ampere)",
             vram_gb=12, vram_type="GDDR6X", bus_width_bits=384,
             base_clock_mhz=1365, boost_clock_mhz=1665,
             shaders=10240, rt_cores=80, tensor_cores=320,
             tdp_watts=350, min_psu_watts=850,
             power_connectors="8pin,8pin", card_length_mm=285, card_slots=2.0,
             pcie_interface="PCIe 4.0 x16", ray_tracing=True, dlss_version="2.0",
             display_outputs="HDMI,DP,DP,DP", msrp_usd=1199),

        dict(name="NVIDIA GeForce RTX 3090",
             brand="NVIDIA", architecture="Ampere", series="RTX 30 Series (Ampere)",
             vram_gb=24, vram_type="GDDR6X", bus_width_bits=384,
             base_clock_mhz=1395, boost_clock_mhz=1695,
             shaders=10496, rt_cores=82, tensor_cores=328,
             tdp_watts=350, min_psu_watts=850,
             power_connectors="8pin,8pin", card_length_mm=313, card_slots=2.0,
             pcie_interface="PCIe 4.0 x16", ray_tracing=True, dlss_version="2.0",
             display_outputs="HDMI,DP,DP,DP", msrp_usd=1499),

        dict(name="NVIDIA GeForce RTX 3090 Ti",
             brand="NVIDIA", architecture="Ampere", series="RTX 30 Series (Ampere)",
             vram_gb=24, vram_type="GDDR6X", bus_width_bits=384,
             base_clock_mhz=1560, boost_clock_mhz=1860,
             shaders=10752, rt_cores=84, tensor_cores=336,
             tdp_watts=450, min_psu_watts=1000,
             power_connectors="8pin,8pin", card_length_mm=313, card_slots=2.0,
             pcie_interface="PCIe 4.0 x16", ray_tracing=True, dlss_version="2.0",
             display_outputs="HDMI,DP,DP,DP", msrp_usd=1999),

        dict(name="NVIDIA GeForce RTX 4060",
             brand="NVIDIA", architecture="Ada Lovelace", series="RTX 40 Series (Ada Lovelace)",
             vram_gb=8, vram_type="GDDR6", bus_width_bits=128,
             base_clock_mhz=1830, boost_clock_mhz=2460,
             shaders=3072, rt_cores=24, tensor_cores=96,
             tdp_watts=115, min_psu_watts=550,
             power_connectors="8pin", card_length_mm=199, card_slots=2.0,
             pcie_interface="PCIe 4.0 x16", ray_tracing=True, dlss_version="3.5",
             display_outputs="HDMI,DP,DP,DP", msrp_usd=299),

        dict(name="NVIDIA GeForce RTX 4060 Ti",
             brand="NVIDIA", architecture="Ada Lovelace", series="RTX 40 Series (Ada Lovelace)",
             vram_gb=8, vram_type="GDDR6", bus_width_bits=128,
             base_clock_mhz=2310, boost_clock_mhz=2535,
             shaders=4352, rt_cores=34, tensor_cores=136,
             tdp_watts=160, min_psu_watts=550,
             power_connectors="8pin", card_length_mm=242, card_slots=2.0,
             pcie_interface="PCIe 4.0 x16", ray_tracing=True, dlss_version="3.5",
             display_outputs="HDMI,DP,DP,DP", msrp_usd=399),

        dict(name="NVIDIA GeForce RTX 4070",
             brand="NVIDIA", architecture="Ada Lovelace", series="RTX 40 Series (Ada Lovelace)",
             vram_gb=12, vram_type="GDDR6X", bus_width_bits=192,
             base_clock_mhz=1920, boost_clock_mhz=2475,
             shaders=5888, rt_cores=46, tensor_cores=184,
             tdp_watts=200, min_psu_watts=650,
             power_connectors="12pin", card_length_mm=242, card_slots=2.0,
             pcie_interface="PCIe 4.0 x16", ray_tracing=True, dlss_version="3.5",
             display_outputs="HDMI,DP,DP,DP", msrp_usd=499),

        dict(name="NVIDIA GeForce RTX 4070 SUPER",
             brand="NVIDIA", architecture="Ada Lovelace", series="RTX 40 Series (Ada Lovelace)",
             vram_gb=12, vram_type="GDDR6X", bus_width_bits=192,
             base_clock_mhz=1980, boost_clock_mhz=2475,
             shaders=7168, rt_cores=56, tensor_cores=224,
             tdp_watts=220, min_psu_watts=650,
             power_connectors="12pin", card_length_mm=249, card_slots=2.5,
             pcie_interface="PCIe 4.0 x16", ray_tracing=True, dlss_version="3.5",
             display_outputs="HDMI,DP,DP,DP", msrp_usd=599),

        dict(name="NVIDIA GeForce RTX 4070 Ti",
             brand="NVIDIA", architecture="Ada Lovelace", series="RTX 40 Series (Ada Lovelace)",
             vram_gb=12, vram_type="GDDR6X", bus_width_bits=192,
             base_clock_mhz=2310, boost_clock_mhz=2610,
             shaders=7680, rt_cores=60, tensor_cores=240,
             tdp_watts=285, min_psu_watts=700,
             power_connectors="16pin", card_length_mm=267, card_slots=2.5,
             pcie_interface="PCIe 4.0 x16", ray_tracing=True, dlss_version="3.5",
             display_outputs="HDMI,DP,DP,DP", msrp_usd=799),

        dict(name="NVIDIA GeForce RTX 4070 Ti SUPER",
             brand="NVIDIA", architecture="Ada Lovelace", series="RTX 40 Series (Ada Lovelace)",
             vram_gb=16, vram_type="GDDR6X", bus_width_bits=256,
             base_clock_mhz=2340, boost_clock_mhz=2610,
             shaders=8448, rt_cores=66, tensor_cores=264,
             tdp_watts=285, min_psu_watts=750,
             power_connectors="16pin", card_length_mm=267, card_slots=2.5,
             pcie_interface="PCIe 4.0 x16", ray_tracing=True, dlss_version="3.5",
             display_outputs="HDMI,DP,DP,DP", msrp_usd=999),

        dict(name="NVIDIA GeForce RTX 4080",
             brand="NVIDIA", architecture="Ada Lovelace", series="RTX 40 Series (Ada Lovelace)",
             vram_gb=16, vram_type="GDDR6X", bus_width_bits=256,
             base_clock_mhz=2205, boost_clock_mhz=2505,
             shaders=9728, rt_cores=76, tensor_cores=304,
             tdp_watts=320, min_psu_watts=750,
             power_connectors="16pin", card_length_mm=304, card_slots=3.0,
             pcie_interface="PCIe 4.0 x16", ray_tracing=True, dlss_version="3.5",
             display_outputs="HDMI,DP,DP,DP", msrp_usd=1199),

        dict(name="NVIDIA GeForce RTX 4080 SUPER",
             brand="NVIDIA", architecture="Ada Lovelace", series="RTX 40 Series (Ada Lovelace)",
             vram_gb=16, vram_type="GDDR6X", bus_width_bits=256,
             base_clock_mhz=2295, boost_clock_mhz=2550,
             shaders=10240, rt_cores=80, tensor_cores=320,
             tdp_watts=320, min_psu_watts=750,
             power_connectors="16pin", card_length_mm=304, card_slots=3.0,
             pcie_interface="PCIe 4.0 x16", ray_tracing=True, dlss_version="3.5",
             display_outputs="HDMI,DP,DP,DP", msrp_usd=999),

        dict(name="NVIDIA GeForce RTX 4090",
             brand="NVIDIA", architecture="Ada Lovelace", series="RTX 40 Series (Ada Lovelace)",
             vram_gb=24, vram_type="GDDR6X", bus_width_bits=384,
             base_clock_mhz=2235, boost_clock_mhz=2520,
             shaders=16384, rt_cores=128, tensor_cores=512,
             tdp_watts=450, min_psu_watts=850,
             power_connectors="16pin", card_length_mm=304, card_slots=3.0,
             pcie_interface="PCIe 4.0 x16", ray_tracing=True, dlss_version="3.5",
             display_outputs="HDMI,DP,DP,DP", msrp_usd=1599),

        dict(name="NVIDIA GeForce RTX 5050",
             brand="NVIDIA", architecture="Blackwell", series="RTX 50 Series (Blackwell)",
             vram_gb=8, vram_type="GDDR6", bus_width_bits=128,
             base_clock_mhz=2317, boost_clock_mhz=2572,
             shaders=3072, rt_cores=24, tensor_cores=96,
             tdp_watts=130, min_psu_watts=550,
             power_connectors=None, card_length_mm=199, card_slots=2.0,
             pcie_interface="PCIe 5.0 x16", ray_tracing=True, dlss_version="4",
             display_outputs="HDMI,DP,DP", msrp_usd=249),

        dict(name="NVIDIA GeForce RTX 5060",
             brand="NVIDIA", architecture="Blackwell", series="RTX 50 Series (Blackwell)",
             vram_gb=8, vram_type="GDDR7", bus_width_bits=128,
             base_clock_mhz=2280, boost_clock_mhz=2497,
             shaders=3840, rt_cores=30, tensor_cores=120,
             tdp_watts=145, min_psu_watts=550,
             power_connectors="8pin", card_length_mm=242, card_slots=2.0,
             pcie_interface="PCIe 5.0 x16", ray_tracing=True, dlss_version="4",
             display_outputs="HDMI,DP,DP,DP", msrp_usd=299),

        dict(name="NVIDIA GeForce RTX 5060 Ti",
             brand="NVIDIA", architecture="Blackwell", series="RTX 50 Series (Blackwell)",
             vram_gb=16, vram_type="GDDR7", bus_width_bits=128,
             base_clock_mhz=2407, boost_clock_mhz=2572,
             shaders=4608, rt_cores=36, tensor_cores=144,
             tdp_watts=180, min_psu_watts=650,
             power_connectors="8pin", card_length_mm=242, card_slots=2.0,
             pcie_interface="PCIe 5.0 x16", ray_tracing=True, dlss_version="4",
             display_outputs="HDMI,DP,DP,DP", msrp_usd=379),

        dict(name="NVIDIA GeForce RTX 5070",
             brand="NVIDIA", architecture="Blackwell", series="RTX 50 Series (Blackwell)",
             vram_gb=12, vram_type="GDDR7", bus_width_bits=192,
             base_clock_mhz=2325, boost_clock_mhz=2512,
             shaders=6144, rt_cores=48, tensor_cores=192,
             tdp_watts=250, min_psu_watts=650,
             power_connectors="16pin", card_length_mm=242, card_slots=2.5,
             pcie_interface="PCIe 5.0 x16", ray_tracing=True, dlss_version="4",
             display_outputs="HDMI,DP,DP,DP", msrp_usd=549),

        dict(name="NVIDIA GeForce RTX 5070 Ti",
             brand="NVIDIA", architecture="Blackwell", series="RTX 50 Series (Blackwell)",
             vram_gb=16, vram_type="GDDR7", bus_width_bits=256,
             base_clock_mhz=2300, boost_clock_mhz=2452,
             shaders=8960, rt_cores=70, tensor_cores=280,
             tdp_watts=300, min_psu_watts=750,
             power_connectors="16pin", card_length_mm=267, card_slots=2.5,
             pcie_interface="PCIe 5.0 x16", ray_tracing=True, dlss_version="4",
             display_outputs="HDMI,DP,DP,DP", msrp_usd=749),

        dict(name="NVIDIA GeForce RTX 5080",
             brand="NVIDIA", architecture="Blackwell", series="RTX 50 Series (Blackwell)",
             vram_gb=16, vram_type="GDDR7", bus_width_bits=256,
             base_clock_mhz=2295, boost_clock_mhz=2617,
             shaders=10752, rt_cores=84, tensor_cores=336,
             tdp_watts=360, min_psu_watts=850,
             power_connectors="16pin", card_length_mm=280, card_slots=2.5,
             pcie_interface="PCIe 5.0 x16", ray_tracing=True, dlss_version="4",
             display_outputs="HDMI,DP,DP,DP", msrp_usd=999),

        dict(name="NVIDIA GeForce RTX 5090",
             brand="NVIDIA", architecture="Blackwell", series="RTX 50 Series (Blackwell)",
             vram_gb=32, vram_type="GDDR7", bus_width_bits=512,
             base_clock_mhz=2017, boost_clock_mhz=2407,
             shaders=21760, rt_cores=170, tensor_cores=680,
             tdp_watts=575, min_psu_watts=1000,
             power_connectors="16pin", card_length_mm=304, card_slots=3.0,
             pcie_interface="PCIe 5.0 x16", ray_tracing=True, dlss_version="4",
             display_outputs="HDMI,DP,DP,DP", msrp_usd=1999),
    ])
    db.session.commit()
